#!/usr/bin/python3 -I
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Wrapper installed at /usr/local/bin/hermes that enforces the runtime
# environment secret boundary for `hermes gateway` (NVIDIA/NemoClaw#4975) and
# masks credential-shaped values in `hermes config show` output.
#
# Why a Python wrapper, not a bash one:
#   - Python 3 invoked with `-I` (isolated mode) ignores PYTHONPATH, PYTHONHOME,
#     user site-packages, and other env-driven startup hooks. It has no
#     equivalent of bash's `BASH_ENV`/`ENV` mechanism that would let a hostile
#     runtime environment source attacker-controlled code before our logic
#     runs. Combined with the absolute shebang (`#!/usr/bin/python3 -I`),
#     the wrapper entrypoint is independent of caller-controlled startup
#     files.
#   - The wrapper resolves the real binary, the validator script, and the
#     trusted python3 interpreter from fixed absolute paths, never from the
#     environment, so an untrusted PATH cannot redirect any of them. The dev
#     fallback resolves against this script's own directory so a checkout
#     works without an install, matching the resolution that
#     `agents/hermes/start.sh` uses for `_HERMES_BOUNDARY_VALIDATOR`.
#
# Source-of-truth note for the `config show` masking layer (reported leak is
# tracked in NVIDIA/NemoClaw#5981; the runtime-env guard for `hermes gateway`
# was added in NVIDIA/NemoClaw#4975):
#   - Invalid state: the upstream Hermes CLI prints inline provider `api_key`
#     values verbatim when asked to render the resolved configuration, so a
#     user running `hermes config show` sees an `sk-`-prefixed string that
#     looks like a real credential.
#   - Value being masked: for configs generated by
#     `agents/hermes/config/hermes-config.ts:buildHermesConfig`, the literal
#     placeholder `sk-OPENSHELL-PROXY-REWRITE` is hard-coded for the `model`,
#     `providers`, and `custom_providers` `api_key` fields; the user's real
#     provider credential is never serialised into the rendered config
#     (requests are rewritten at the OpenShell egress boundary). The masker
#     also unconditionally redacts any `api_key`-shaped field — including a
#     real value supplied via the seed-routing fallback in
#     `agents/hermes/seed-dashboard-config.py:_route_api_key` — so the
#     post-mask user-visible stream is safe in every case.
#   - Source-fix constraint: removing the inline `api_key` would require
#     either Hermes CLI native env-var reference support (an upstream
#     change) or a redesigned dashboard/runtime contract that no longer
#     needs an `sk-`-prefixed placeholder in the rendered config.
#   - Regression test: `test/hermes-gateway-wrapper.test.ts` —
#     `masks every api_key emitted by buildHermesConfig ...` derives a
#     fixture from `buildHermesConfig()` and asserts no raw placeholder
#     survives in stdout for `config show`.
#   - Removal condition: delete the `config show` branch when Hermes CLI
#     redacts credential-shaped fields natively or `buildHermesConfig` stops
#     emitting an inline `api_key` value.
#
# Scope of the masker: structured key-labelled secret fields (api_key,
# api_secret, access_token, auth_token, client_secret, secret_key, secret,
# token, password, bearer, authorization, credential — including
# hyphen/underscore/camelCase variants) in Python-dict, JSON, YAML key:value,
# env-style key=value, and YAML block-scalar shapes; plus, as defence in
# depth, every free-form `sk-`-prefixed token of length >= 8. Non-`sk-`
# token families in free prose are not redacted — that is the upstream
# Hermes CLI's responsibility.
#
# The same gateway runtime-env guard also runs in the nemoclaw-start
# entrypoint (`agents/hermes/start.sh:validate_hermes_runtime_env_secret_boundary`)
# and in the host-side gateway recovery path, but a direct
# `docker exec ... hermes gateway run` invocation bypasses the entrypoint
# entirely, so it would start the gateway with raw secret-shaped env vars
# (e.g. `SLACK_BOT_TOKEN=xoxb-real-...`). Wrapping the binary closes that
# bypass: every path that launches the gateway now passes through the same
# single-source-of-truth validator before the port is bound.
#
# Only the `gateway` and `config show` subcommands are intercepted; all
# other hermes subcommands (dashboard, --version, ...) pass straight
# through unchanged.

import os
import subprocess
import sys

_INSTALLED_REAL = "/usr/local/bin/hermes.real"
_INSTALLED_GUARD = "/usr/local/lib/nemoclaw/validate-hermes-env-secret-boundary.py"
# The Dockerfile installs the validator under the hermes-prefixed name even
# though the repository source stays at `validate-env-secret-boundary.py`.
# Mirror the same dev-fallback `start.sh` uses so an ad-hoc bash invocation
# over a checkout still finds the guard.
_GUARD_DEV_FILENAME = "validate-env-secret-boundary.py"
# Trusted absolute paths for the python3 interpreter, ordered most-preferred
# first. The resolver returns the first executable match (first-wins); the
# same priority is mirrored by `agents/hermes/start.sh:resolve_trusted_python3`
# so both entry points pick the same interpreter when several are present.
# Venv first matches the security principle of preferring the most controlled
# environment; fall back to system python3 when the sandbox image has no venv
# yet.
_TRUSTED_PYTHON3 = (
    "/opt/hermes/.venv/bin/python3",
    "/usr/local/bin/python3",
    "/usr/bin/python3",
)


def _self_dir() -> str:
    return os.path.dirname(os.path.realpath(__file__))


def _resolve_real_hermes() -> str:
    if os.access(_INSTALLED_REAL, os.X_OK):
        return _INSTALLED_REAL
    return os.path.join(_self_dir(), "hermes.real")


def _resolve_guard() -> str:
    if os.path.isfile(_INSTALLED_GUARD):
        return _INSTALLED_GUARD
    return os.path.join(_self_dir(), _GUARD_DEV_FILENAME)


def _resolve_trusted_python3() -> str | None:
    for candidate in _TRUSTED_PYTHON3:
        if os.access(candidate, os.X_OK):
            return candidate
    return None


_MASKER_STDERR_ALLOWED_PREFIX = "[SECURITY]"


def _forward_sanitised_masker_stderr(raw: bytes, fallback: str) -> None:
    # Only forward lines that match the documented `[SECURITY] ...` prefix from
    # the masker itself. Anything else (Python tracebacks, import errors, OOM
    # messages) is dropped and replaced with a generic notice so internal file
    # paths and stack frames cannot leak through the user's terminal on an
    # unhandled exception.
    text = raw.decode("utf-8", errors="replace")
    safe_lines = [
        line for line in text.splitlines() if line.startswith(_MASKER_STDERR_ALLOWED_PREFIX)
    ]
    if safe_lines:
        sys.stderr.write("\n".join(safe_lines) + "\n")
    else:
        sys.stderr.write(fallback + "\n")


def _run_config_show(real_hermes: str, guard_path: str, argv: list[str]) -> int:
    python3 = _resolve_trusted_python3()
    if python3 is None:
        print(
            "[SECURITY] Refusing hermes config show: no python3 at a trusted absolute path to run the output masker",
            file=sys.stderr,
        )
        return 127
    # The masker reads its stdin and writes the redacted stream to its own
    # stdout. We spawn one masker per Hermes stream and pipe Hermes' raw
    # bytes through it. Closing the parent's reference to each masker's
    # stdin pipe (after `real_hermes` inherits the FD) makes the masker see
    # EOF when Hermes finishes writing. The masker itself buffers in
    # memory and only writes on success, so a mid-stream crash never
    # produces a partial secret on either stream. Each masker's own stderr
    # is captured to a pipe so we can filter it before forwarding — a
    # raw `stderr=sys.stderr.fileno()` would leak Python tracebacks on an
    # unhandled exception.
    masker_argv = [python3, "-I", guard_path, "mask-config-output"]
    masker_stdout = subprocess.Popen(
        masker_argv,
        stdin=subprocess.PIPE,
        stdout=sys.stdout.fileno(),
        stderr=subprocess.PIPE,
    )
    masker_stderr = subprocess.Popen(
        masker_argv,
        stdin=subprocess.PIPE,
        stdout=sys.stderr.fileno(),
        stderr=subprocess.PIPE,
    )
    try:
        proc = subprocess.Popen(
            [real_hermes, *argv],
            stdout=masker_stdout.stdin,
            stderr=masker_stderr.stdin,
        )
    finally:
        if masker_stdout.stdin is not None:
            masker_stdout.stdin.close()
        if masker_stderr.stdin is not None:
            masker_stderr.stdin.close()
    proc.wait()
    # Read each masker's captured stderr before wait() returns so the
    # pipe drains and the masker is not blocked writing into a full buffer.
    # communicate() cannot be used here because the stdin pipe was already
    # closed for ownership transfer.
    stdout_masker_stderr = masker_stdout.stderr.read() if masker_stdout.stderr else b""
    stderr_masker_stderr = masker_stderr.stderr.read() if masker_stderr.stderr else b""
    masker_stdout.wait()
    masker_stderr.wait()
    if masker_stdout.returncode != 0:
        _forward_sanitised_masker_stderr(
            stdout_masker_stderr,
            "[SECURITY] Refusing hermes config show: output masker failed (stdout)",
        )
        return masker_stdout.returncode
    if masker_stderr.returncode != 0:
        _forward_sanitised_masker_stderr(
            stderr_masker_stderr,
            "[SECURITY] Refusing hermes config show: output masker failed (stderr)",
        )
        return masker_stderr.returncode
    return proc.returncode


def _run_gateway_guard(guard_path: str) -> int:
    python3 = _resolve_trusted_python3()
    if python3 is None:
        print(
            "[SECURITY] Refusing hermes gateway: no python3 at a trusted absolute path to run the secret-boundary guard",
            file=sys.stderr,
        )
        return 127
    return subprocess.call([python3, "-I", guard_path, "runtime-env"])


def main(argv: list[str]) -> int:
    real_hermes = _resolve_real_hermes()
    guard_path = _resolve_guard()
    if argv[:2] == ["config", "show"]:
        return _run_config_show(real_hermes, guard_path, argv)
    if argv[:1] == ["gateway"]:
        rc = _run_gateway_guard(guard_path)
        if rc != 0:
            return rc
    os.execv(real_hermes, [real_hermes, *argv])
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
