#!/usr/bin/python3 -I
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Wrapper installed at /usr/local/bin/hermes that enforces the runtime
# environment secret boundary for `hermes gateway` (NVIDIA/NemoClaw#4975) and
# masks credential-shaped values in `hermes config show` output.
#
# Why a Python wrapper, not a bash one:
#   - Python 3 invoked with `-I` (isolated mode) ignores PYTHONPATH, PYTHONHOME,
#     user site-packages, and other env-driven startup hooks. It has no
#     equivalent of bash's `BASH_ENV`/`ENV` mechanism that would let a hostile
#     runtime environment source attacker-controlled code before our logic
#     runs. Combined with the absolute shebang (`#!/usr/bin/python3 -I`),
#     the wrapper entrypoint is independent of caller-controlled startup
#     files.
#   - The wrapper resolves the real binary, the validator script, and the
#     trusted python3 interpreter from fixed absolute paths, never from the
#     environment, so an untrusted PATH cannot redirect any of them. The dev
#     fallback resolves against this script's own directory so a checkout
#     works without an install, matching the resolution that
#     `agents/hermes/start.sh` uses for `_HERMES_BOUNDARY_VALIDATOR`.
#
# Source-of-truth note for the `config show` masking layer (reported leak is
# tracked in NVIDIA/NemoClaw#5981; the runtime-env guard for `hermes gateway`
# was added in NVIDIA/NemoClaw#4975):
#   - Invalid state: the upstream Hermes CLI prints inline provider `api_key`
#     values verbatim when asked to render the resolved configuration, so a
#     user running `hermes config show` sees an `sk-`-prefixed string that
#     looks like a real credential.
#   - Value being masked: for configs generated by
#     `agents/hermes/config/managed-policy.ts:buildHermesManagedPolicy`, the literal
#     rewrite sentinel `sk-OPENSHELL-PROXY-REWRITE` is hard-coded for the `model`,
#     `providers`, and `custom_providers` `api_key` fields; the user's real
#     provider credential is never serialised into the rendered config
#     (requests are rewritten at the OpenShell egress boundary). The masker
#     also unconditionally redacts any `api_key`-shaped field, so no
#     `api_key` field value reaches the post-mask user-visible stream.
#   - Source-fix constraint: removing the inline `api_key` would require
#     either Hermes CLI native env-var reference support (an upstream
#     change) or a redesigned dashboard/runtime contract that no longer
#     needs an `sk-`-prefixed rewrite sentinel in the rendered config.
#   - Regression test: `test/agents/hermes/hermes-gateway-wrapper.test.ts` —
#     `masks every api_key emitted by the managed policy ...` derives a
#     fixture from `buildHermesManagedPolicy()` and asserts no raw sentinel
#     survives in stdout for `config show`.
#   - Removal condition: delete the `config show` branch when Hermes CLI
#     redacts credential-shaped fields natively or `buildHermesManagedPolicy`
#     stops emitting an inline `api_key` value.
#
# `hermes-cli-adapter-v1.json` owns the exact translated command forms, their
# upstream version, rationale, and removal conditions. The image build validates
# that contract against Hermes' machine-readable top-level and chat parser
# metadata. The wrapper reads session-name command boundaries from Hermes'
# installed coalescer source, parses a managed invocation once from the contract,
# and passes all unrelated commands through without a copied subcommand inventory.
#
# Scope of the masker: structured key-labelled secret fields (api_key,
# api_secret, access_token, auth_token, client_secret, secret_key, secret,
# token, password, bearer, authorization, credential — including
# hyphen/underscore/camelCase variants) in Python-dict, JSON, YAML key:value,
# env-style key=value, and YAML block-scalar shapes (`|`, `|-`, `|+`, `|2`,
# `|2-`, `|2+`, `|-2`, and folded `>` equivalents); plus, as defence in depth,
# every free-form `sk-`-prefixed token of length >= 8. Non-`sk-` token families
# in free prose are not redacted — that is the upstream Hermes CLI's
# responsibility.
#
# The same gateway runtime-env guard also runs in the nemoclaw-start
# entrypoint (`agents/hermes/start.sh:validate_hermes_runtime_env_secret_boundary`)
# and in the host-side gateway recovery path, but a direct
# `docker exec ... hermes gateway run` invocation bypasses the entrypoint
# entirely, so it would start the gateway with raw secret-shaped env vars
# (e.g. `SLACK_BOT_TOKEN=xoxb-real-...`). Wrapping the binary closes that
# bypass: every path that launches the gateway now passes through the same
# single-source-of-truth validator before the port is bound.
#
# Only a small set of top-level commands are intercepted. Managed dashboard
# launches receive the local API bearer token through process environment after
# a descriptor-safe read, so the isolated dashboard home does not need a second
# credential-bearing dotenv file. Other subcommands pass through unchanged.

import ast
import json
import os
import re
import stat
import subprocess
import sys
import tempfile

_INSTALLED_REAL = "/usr/local/bin/hermes.real"
_INSTALLED_GUARD = "/usr/local/lib/nemoclaw/validate-hermes-env-secret-boundary.py"
_INSTALLED_CLI_ADAPTER = "/usr/local/share/nemoclaw/hermes-cli-adapter-v1.json"
_INSTALLED_HERMES_MAIN = "/opt/hermes/hermes_cli/main.py"
# The Dockerfile installs the validator under the hermes-prefixed name even
# though the repository source stays at `validate-env-secret-boundary.py`.
# Mirror the same dev-fallback `start.sh` uses so an ad-hoc bash invocation
# over a checkout still finds the guard.
_GUARD_DEV_FILENAME = "validate-env-secret-boundary.py"
_DASHBOARD_API_SERVER_ENV_PATH = "NEMOCLAW_HERMES_DASHBOARD_API_SERVER_ENV"
_API_SERVER_KEY_RE = re.compile(r"^[0-9a-f]{64}$")
_CLI_ADAPTER_DEV_FILENAME = "hermes-cli-adapter-v1.json"
_HERMES_MAIN_DEV_FILENAME = "hermes-main.py"
# Trusted absolute paths for the python3 interpreter, ordered most-preferred
# first. The resolver returns the first executable match (first-wins); the
# same priority is mirrored by `agents/hermes/start.sh:resolve_trusted_python3`
# so both entry points pick the same interpreter when several are present.
# Venv first matches the security principle of preferring the most controlled
# environment; fall back to system python3 when the sandbox image has no venv
# yet.
_TRUSTED_PYTHON3 = (
    "/opt/hermes/.venv/bin/python3",
    "/usr/local/bin/python3",
    "/usr/bin/python3",
)


def _self_dir() -> str:
    return os.path.dirname(os.path.realpath(__file__))


def _resolve_real_hermes() -> str:
    if os.access(_INSTALLED_REAL, os.X_OK):
        return _INSTALLED_REAL
    return os.path.join(_self_dir(), "hermes.real")


def _resolve_guard() -> str:
    if os.path.isfile(_INSTALLED_GUARD):
        return _INSTALLED_GUARD
    return os.path.join(_self_dir(), _GUARD_DEV_FILENAME)


def _resolve_cli_adapter() -> str:
    if os.path.isfile(_INSTALLED_CLI_ADAPTER):
        return _INSTALLED_CLI_ADAPTER
    return os.path.join(_self_dir(), _CLI_ADAPTER_DEV_FILENAME)


def _resolve_hermes_main() -> str:
    if os.path.isfile(_INSTALLED_HERMES_MAIN):
        return _INSTALLED_HERMES_MAIN
    return os.path.join(_self_dir(), _HERMES_MAIN_DEV_FILENAME)


def _resolve_trusted_python3() -> str | None:
    for candidate in _TRUSTED_PYTHON3:
        if os.access(candidate, os.X_OK):
            return candidate
    return None


def _load_dashboard_api_server_key() -> bool:
    """Load a managed dashboard token when startup supplies its source path.

    Direct, unmanaged ``hermes dashboard`` invocations preserve the upstream optional API
    authentication behavior. Managed startup always supplies the gateway dotenv path
    and fails closed when its generated token is absent or invalid.
    """
    source_path = os.environ.pop(_DASHBOARD_API_SERVER_ENV_PATH, "")
    if not source_path:
        return True

    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    fd = -1
    try:
        fd = os.open(source_path, flags)
        source_stat = os.fstat(fd)
        if not stat.S_ISREG(source_stat.st_mode):
            raise ValueError("credential source is not a regular file")
        with os.fdopen(fd, "r", encoding="utf-8", closefd=False) as handle:
            values: list[str] = []
            for line in handle:
                candidate = line.strip()
                if candidate.startswith("export "):
                    candidate = candidate[len("export ") :].lstrip()
                key, separator, value = candidate.partition("=")
                if not separator or key.strip() != "API_SERVER_KEY":
                    continue
                value = value.strip()
                if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
                    value = value[1:-1]
                values.append(value)
        if len(values) != 1 or _API_SERVER_KEY_RE.fullmatch(values[0]) is None:
            raise ValueError("credential source has no unique generated token")
    except (OSError, UnicodeError, ValueError):
        print(
            "[SECURITY] Refusing hermes dashboard: API server credential source "
            "is invalid or unreadable",
            file=sys.stderr,
        )
        return False
    finally:
        if fd >= 0:
            try:
                os.close(fd)
            except OSError:
                # Never retry close: EINTR leaves descriptor state unspecified,
                # and O_CLOEXEC keeps the source out of the dashboard process.
                pass

    os.environ["API_SERVER_KEY"] = values[0]
    return True


_MASKER_STDERR_ALLOWED_PREFIX = "[SECURITY]"
_MASKER_STDERR_MAX_BYTES = 10 * 1024 * 1024


def _read_masker_stderr(file_obj, stream_name: str) -> tuple[bytes, bool]:
    file_obj.seek(0)
    raw = file_obj.read(_MASKER_STDERR_MAX_BYTES + 1)
    if len(raw) > _MASKER_STDERR_MAX_BYTES:
        print(
            f"[SECURITY] Refusing hermes config show: output masker stderr exceeded {_MASKER_STDERR_MAX_BYTES} bytes ({stream_name})",
            file=sys.stderr,
        )
        return raw[:_MASKER_STDERR_MAX_BYTES], True
    return raw, False


def _forward_sanitised_masker_stderr(raw: bytes, fallback: str) -> None:
    # Only forward lines that match the documented `[SECURITY] ...` prefix from
    # the masker itself. Anything else (Python tracebacks, import errors, OOM
    # messages) is dropped and replaced with a generic notice so internal file
    # paths and stack frames cannot leak through the user's terminal on an
    # unhandled exception.
    text = raw.decode("utf-8", errors="replace")
    safe_lines = [
        line for line in text.splitlines() if line.startswith(_MASKER_STDERR_ALLOWED_PREFIX)
    ]
    if safe_lines:
        sys.stderr.write("\n".join(safe_lines) + "\n")
    else:
        sys.stderr.write(fallback + "\n")


def _run_config_show(real_hermes: str, guard_path: str, argv: list[str]) -> int:
    python3 = _resolve_trusted_python3()
    if python3 is None:
        print(
            "[SECURITY] Refusing hermes config show: no python3 at a trusted absolute path to run the output masker",
            file=sys.stderr,
        )
        return 127
    # The masker reads its stdin and writes the redacted stream to its own
    # stdout. We spawn one masker per Hermes stream and pipe Hermes' raw
    # bytes through it. Closing the parent's reference to each masker's
    # stdin pipe (after `real_hermes` inherits the FD) makes the masker see
    # EOF when Hermes finishes writing. The masker itself buffers in
    # memory and only writes on success, so a mid-stream crash never
    # produces a partial secret on either stream. Each masker's own stderr
    # is captured to a temporary file so we can filter it before forwarding — a
    # raw `stderr=sys.stderr.fileno()` would leak Python tracebacks on an
    # unhandled exception, while a pipe could deadlock if a masker writes a
    # large diagnostic before the parent drains it.
    masker_argv = [python3, "-I", guard_path, "mask-config-output"]
    with (
        tempfile.TemporaryFile() as stdout_masker_stderr_file,
        tempfile.TemporaryFile() as stderr_masker_stderr_file,
    ):
        masker_stdout = subprocess.Popen(
            masker_argv,
            stdin=subprocess.PIPE,
            stdout=sys.stdout.fileno(),
            stderr=stdout_masker_stderr_file,
        )
        masker_stderr = subprocess.Popen(
            masker_argv,
            stdin=subprocess.PIPE,
            stdout=sys.stderr.fileno(),
            stderr=stderr_masker_stderr_file,
        )
        try:
            proc = subprocess.Popen(
                [real_hermes, *argv],
                stdout=masker_stdout.stdin,
                stderr=masker_stderr.stdin,
            )
        except OSError as exc:
            if masker_stdout.stdin is not None:
                masker_stdout.stdin.close()
            if masker_stderr.stdin is not None:
                masker_stderr.stdin.close()
            for masker in (masker_stdout, masker_stderr):
                try:
                    masker.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    masker.terminate()
                    masker.wait(timeout=5)
            print(
                "[SECURITY] Refusing hermes config show: failed to exec Hermes "
                f"({exc.__class__.__name__})",
                file=sys.stderr,
            )
            return 126
        else:
            if masker_stdout.stdin is not None:
                masker_stdout.stdin.close()
            if masker_stderr.stdin is not None:
                masker_stderr.stdin.close()
        proc.wait()
        masker_stdout.wait()
        masker_stderr.wait()
        stdout_masker_stderr, stdout_masker_stderr_too_large = _read_masker_stderr(
            stdout_masker_stderr_file,
            "stdout",
        )
        stderr_masker_stderr, stderr_masker_stderr_too_large = _read_masker_stderr(
            stderr_masker_stderr_file,
            "stderr",
        )
    if stdout_masker_stderr_too_large or stderr_masker_stderr_too_large:
        return 1
    if masker_stdout.returncode != 0:
        _forward_sanitised_masker_stderr(
            stdout_masker_stderr,
            "[SECURITY] Refusing hermes config show: output masker failed (stdout)",
        )
        return masker_stdout.returncode
    if masker_stderr.returncode != 0:
        _forward_sanitised_masker_stderr(
            stderr_masker_stderr,
            "[SECURITY] Refusing hermes config show: output masker failed (stderr)",
        )
        return masker_stderr.returncode
    return proc.returncode


def _run_gateway_guard(guard_path: str) -> int:
    python3 = _resolve_trusted_python3()
    if python3 is None:
        print(
            "[SECURITY] Refusing hermes gateway: no python3 at a trusted absolute path to run the secret-boundary guard",
            file=sys.stderr,
        )
        return 127
    return subprocess.call([python3, "-I", guard_path, "runtime-env"])


_SUPPORTED_CLI_ADAPTER_VERSION = 1
_CLI_VERSION_PROBE_ENV = "NEMOCLAW_HERMES_ADAPTER_VERSION_PROBE"
_CLI_VERSION_PATTERN = re.compile(
    r"^(?:Hermes Agent )?v?([0-9]+[.][0-9]+[.][0-9]+)(?:\b|$)",
    re.MULTILINE,
)
_CLI_ADAPTER_ARITIES = {"boolean", "optional_session", "required", "session"}
_SESSION_NAME_COALESCER = {
    "module": "hermes_cli.main",
    "function": "_coalesce_session_name_args",
    "boundary_set": "_SUBCOMMANDS",
}


class _CliAdapterError(Exception):
    """Signal an invalid adapter contract or incompatible upstream CLI."""


class _CliBinaryExecutionError(_CliAdapterError):
    """Signal that the fixed Hermes binary could not be executed."""


def _load_cli_adapter(path: str) -> dict:
    try:
        with open(path, encoding="utf-8") as adapter_file:
            adapter = json.load(adapter_file)
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise _CliAdapterError(
            f"could not read Hermes CLI adapter ({exc.__class__.__name__})"
        ) from None

    if (
        not isinstance(adapter, dict)
        or adapter.get("adapter_version") != _SUPPORTED_CLI_ADAPTER_VERSION
    ):
        version = adapter.get("adapter_version") if isinstance(adapter, dict) else None
        raise _CliAdapterError(f"unsupported Hermes CLI adapter version: {version!r}")
    if not isinstance(adapter.get("upstream_cli_version"), str):
        raise _CliAdapterError("Hermes CLI adapter has no upstream version")
    if adapter.get("managed_commands") != ["chat"]:
        raise _CliAdapterError("Hermes CLI adapter has unsupported managed commands")
    if adapter.get("session_name_coalescer") != _SESSION_NAME_COALESCER:
        raise _CliAdapterError("Hermes CLI adapter has an unsupported session-name coalescer")

    options = adapter.get("options")
    if not isinstance(options, list) or not options:
        raise _CliAdapterError("Hermes CLI adapter has no managed options")
    ids: set[str] = set()
    names: set[str] = set()
    for option in options:
        if not isinstance(option, dict):
            raise _CliAdapterError("Hermes CLI adapter option is not an object")
        option_id = option.get("id")
        option_names = option.get("names")
        arity = option.get("arity")
        if not isinstance(option_id, str) or not option_id or option_id in ids:
            raise _CliAdapterError("Hermes CLI adapter has an invalid option id")
        if (
            not isinstance(option_names, list)
            or not option_names
            or not all(isinstance(name, str) and name.startswith("-") for name in option_names)
        ):
            raise _CliAdapterError(f"Hermes CLI adapter option {option_id} has invalid names")
        if arity not in _CLI_ADAPTER_ARITIES:
            raise _CliAdapterError(f"Hermes CLI adapter option {option_id} has invalid arity")
        if any(name in names for name in option_names):
            raise _CliAdapterError("Hermes CLI adapter has duplicate option names")
        if arity != "boolean" and not isinstance(option.get("canonical"), str):
            raise _CliAdapterError(f"Hermes CLI adapter option {option_id} has no canonical name")
        ids.add(option_id)
        names.update(option_names)

    required = {"continue", "model", "oneshot", "profile", "provider", "resume", "usage_file"}
    if not required <= ids:
        raise _CliAdapterError("Hermes CLI adapter is missing a managed translation option")
    translations = adapter.get("translations")
    if not isinstance(translations, dict) or set(translations) != {
        "provider_model_composition",
        "resumed_oneshot",
    }:
        raise _CliAdapterError("Hermes CLI adapter has invalid translation metadata")
    return adapter


def _session_name_boundaries(adapter: dict) -> frozenset[str]:
    coalescer = adapter["session_name_coalescer"]
    source_path = _resolve_hermes_main()
    try:
        with open(source_path, encoding="utf-8") as source_file:
            tree = ast.parse(source_file.read(), filename=source_path)
    except (OSError, UnicodeError, SyntaxError) as exc:
        raise _CliAdapterError(
            f"could not read the Hermes session-name coalescer ({exc.__class__.__name__})"
        ) from None

    functions = [
        node
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and node.name == coalescer["function"]
    ]
    if len(functions) != 1:
        raise _CliAdapterError("Hermes session-name coalescer function is incompatible")
    assignments = [
        node
        for node in functions[0].body
        if isinstance(node, ast.Assign)
        and len(node.targets) == 1
        and isinstance(node.targets[0], ast.Name)
        and node.targets[0].id == coalescer["boundary_set"]
    ]
    if len(assignments) != 1:
        raise _CliAdapterError("Hermes session-name coalescer boundary set is incompatible")
    try:
        boundaries = ast.literal_eval(assignments[0].value)
    except (ValueError, TypeError, SyntaxError):
        raise _CliAdapterError("Hermes session-name coalescer boundary set is not literal") from None
    if (
        not isinstance(boundaries, set)
        or not boundaries
        or not all(isinstance(boundary, str) and boundary for boundary in boundaries)
    ):
        raise _CliAdapterError("Hermes session-name coalescer boundary set is invalid")
    return frozenset(boundaries)


def _option_index(adapter: dict) -> tuple[dict[str, dict], dict[str, dict]]:
    by_name: dict[str, dict] = {}
    by_id: dict[str, dict] = {}
    for option in adapter["options"]:
        by_id[option["id"]] = option
        for name in option["names"]:
            by_name[name] = option
    return by_name, by_id


def _has_option(argv: list[str], option: dict) -> bool:
    for arg in argv:
        if arg == "--":
            break
        if arg in option["names"]:
            return True
        if arg.startswith("--") and "=" in arg and arg.split("=", 1)[0] in option["names"]:
            return True
    return False


def _parse_managed_invocation(argv: list[str], adapter: dict) -> dict | None:
    """Parse one managed top-level or chat invocation from the adapter schema."""
    by_name, by_id = _option_index(adapter)
    coalesce_session = _has_option(argv, by_id["oneshot"])
    occurrences: list[dict] = []
    occurrence_ids: dict[str, int] = {}
    command: str | None = None
    session_boundaries: frozenset[str] | None = None
    unknown_option = False
    terminated = False
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "--":
            terminated = True
            break

        option = None
        value: str | None = None
        equals_form = False
        if arg.startswith("--") and "=" in arg:
            name, value = arg.split("=", 1)
            option = by_name.get(name)
            equals_form = option is not None
        else:
            name = arg
            option = by_name.get(name)

        if option is not None:
            option_id = option["id"]
            if occurrence_ids.get(option_id, 0) and not option.get("repeatable", False):
                return None
            arity = option["arity"]
            end = i + 1
            if equals_form:
                if arity == "boolean" or not value:
                    return None
            elif arity == "boolean":
                value = None
            elif arity in {"session", "optional_session"}:
                parts: list[str] = []
                cursor = i + 1
                if cursor < len(argv) and not argv[cursor]:
                    return None
                if cursor < len(argv) and not argv[cursor].startswith("-"):
                    session_boundaries = session_boundaries or _session_name_boundaries(adapter)
                    if argv[cursor] not in session_boundaries:
                        parts.append(argv[cursor])
                        cursor += 1
                    if parts and coalesce_session and command is None:
                        while (
                            cursor < len(argv)
                            and not argv[cursor].startswith("-")
                            and argv[cursor] not in session_boundaries
                        ):
                            parts.append(argv[cursor])
                            cursor += 1
                if not parts and arity == "session":
                    return None
                value = " ".join(parts) if parts else None
                end = cursor
            else:
                if i + 1 >= len(argv) or argv[i + 1].startswith("-") or not argv[i + 1]:
                    return None
                value = argv[i + 1]
                end = i + 2

            occurrences.append(
                {
                    "canonical": option.get("canonical", name),
                    "end": end,
                    "equals": equals_form,
                    "id": option_id,
                    "name": name,
                    "start": i,
                    "value": value,
                }
            )
            occurrence_ids[option_id] = occurrence_ids.get(option_id, 0) + 1
            i = end
            continue

        if command is not None:
            i += 1
            continue
        if arg.startswith("-"):
            # Skip only atomic unknown options; a following positional can be their value.
            if "=" in arg or i + 1 >= len(argv) or argv[i + 1].startswith("-"):
                unknown_option = True
                i += 1
                continue
            return None
        if arg in adapter["managed_commands"]:
            command = arg
            i += 1
            continue
        if session_boundaries is not None and arg in session_boundaries:
            return None
        if (
            occurrence_ids.get("continue", 0) + occurrence_ids.get("resume", 0) == 1
            and _has_option(argv, by_id["provider"])
            and _has_option(argv, by_id["model"])
        ):
            raise _AmbiguousProviderModelSession
        return None

    return {
        "argv": argv,
        "command": command,
        "occurrences": occurrences,
        "terminated": terminated,
        "unknown_option": unknown_option,
    }


def _occurrences(parsed: dict, option_id: str) -> list[dict]:
    return [occurrence for occurrence in parsed["occurrences"] if occurrence["id"] == option_id]


def _merged_model(provider: str, model: str) -> str:
    prefix = f"{provider}/"
    return model if model.casefold().startswith(prefix.casefold()) else f"{provider}/{model}"


def _provider_model_composition(parsed: dict) -> tuple[dict, dict, str] | None:
    providers = _occurrences(parsed, "provider")
    models = _occurrences(parsed, "model")
    if len(providers) != 1 or len(models) != 1:
        return None
    provider = providers[0]
    model = models[0]
    if not provider["value"] or not model["value"]:
        return None
    return provider, model, _merged_model(provider["value"], model["value"])


def _translate_resumed_oneshot(
    parsed: dict,
    composition: tuple[dict, dict, str] | None,
) -> list[str] | None:
    oneshots = _occurrences(parsed, "oneshot")
    resumes = _occurrences(parsed, "resume")
    continues = _occurrences(parsed, "continue")
    if (
        len(oneshots) != 1
        or len(resumes) + len(continues) != 1
        or parsed["command"] is not None
        or parsed["terminated"]
        or parsed["unknown_option"]
    ):
        return None
    if _occurrences(parsed, "usage_file"):
        raise _UnsupportedResumedOneshotUsageFile

    translated: list[str] = []
    profiles = _occurrences(parsed, "profile")
    if profiles:
        translated.extend([profiles[0]["canonical"], profiles[0]["value"]])
    translated.extend(["chat", "--query", oneshots[0]["value"], "--quiet"])

    session = resumes[0] if resumes else continues[0]
    translated.append(session["canonical"])
    if session["value"] is not None:
        translated.append(session["value"])

    provider_occurrence = composition[0] if composition else None
    model_occurrence = composition[1] if composition else None
    merged_model = composition[2] if composition else None
    excluded = {"continue", "oneshot", "profile", "resume", "usage_file"}
    for occurrence in parsed["occurrences"]:
        if occurrence["id"] in excluded or occurrence is provider_occurrence:
            continue
        if occurrence is model_occurrence:
            translated.extend([occurrence["canonical"], merged_model])
        elif occurrence["value"] is None:
            translated.append(occurrence["name"])
        else:
            translated.extend([occurrence["canonical"], occurrence["value"]])
    return translated


class _UnsupportedResumedOneshotUsageFile(Exception):
    """Signal a valid resumed one-shot form whose usage report would be lost."""


class _AmbiguousProviderModelSession(Exception):
    """Signal provider/model flags after an unquoted multi-word session name."""


def _apply_provider_model_composition(
    parsed: dict, composition: tuple[dict, dict, str]
) -> list[str]:
    provider, model, merged_model = composition
    skip = set(range(provider["start"], provider["end"]))
    result: list[str] = []
    for index, arg in enumerate(parsed["argv"]):
        if index in skip:
            continue
        if index == model["start"] and model["equals"]:
            result.append(f"{model['name']}={merged_model}")
        elif index == model["start"] + 1 and not model["equals"]:
            result.append(merged_model)
        else:
            result.append(arg)
    return result


def _adapt_cli_argv(argv: list[str], adapter: dict) -> tuple[str, list[str]]:
    parsed = _parse_managed_invocation(argv, adapter)
    if parsed is None:
        return "passthrough", argv
    composition = _provider_model_composition(parsed)
    translated = _translate_resumed_oneshot(parsed, composition)
    if translated is not None:
        return "translated", translated
    if composition is not None:
        return "translated", _apply_provider_model_composition(parsed, composition)
    return "passthrough", argv


def _require_upstream_cli_version(real_hermes: str, expected: str) -> None:
    env = dict(os.environ)
    env[_CLI_VERSION_PROBE_ENV] = "1"
    try:
        result = subprocess.run(
            [real_hermes, "--version"],
            capture_output=True,
            check=False,
            env=env,
            text=True,
            timeout=10,
        )
    except OSError as exc:
        raise _CliBinaryExecutionError(
            f"failed to exec Hermes binary at {real_hermes}: {exc}"
        ) from None
    except subprocess.TimeoutExpired as exc:
        raise _CliAdapterError(
            f"could not verify the Hermes CLI version ({exc.__class__.__name__})"
        ) from None
    output = f"{result.stdout}\n{result.stderr}"
    match = _CLI_VERSION_PATTERN.search(output)
    actual = match.group(1) if match else None
    if result.returncode != 0 or actual != expected:
        raise _CliAdapterError(
            f"adapter targets Hermes {expected}, installed CLI reports "
            f"{actual or 'an unknown version'}"
        )


def _report_cli_adapter_error(exc: _CliAdapterError) -> int:
    if isinstance(exc, _CliBinaryExecutionError):
        print(f"[SECURITY] Refusing to run hermes: {exc}", file=sys.stderr)
        return 126
    print(f"[COMPATIBILITY] Refusing to run hermes: {exc}", file=sys.stderr)
    return 2


def main(argv: list[str]) -> int:
    real_hermes = _resolve_real_hermes()
    guard_path = _resolve_guard()
    if argv[:1] == ["dashboard"] and not _load_dashboard_api_server_key():
        return 1
    if argv[:2] == ["config", "show"]:
        return _run_config_show(real_hermes, guard_path, argv)
    if argv[:1] == ["gateway"]:
        rc = _run_gateway_guard(guard_path)
        if rc != 0:
            return rc
    try:
        adapter = _load_cli_adapter(_resolve_cli_adapter())
        adapter_result, exec_argv = _adapt_cli_argv(argv, adapter)
        if adapter_result == "translated":
            _require_upstream_cli_version(real_hermes, adapter["upstream_cli_version"])
    except _UnsupportedResumedOneshotUsageFile:
        try:
            _require_upstream_cli_version(real_hermes, adapter["upstream_cli_version"])
        except _CliAdapterError as exc:
            return _report_cli_adapter_error(exc)
        print(
            "[COMPATIBILITY] Refusing resumed one-shot with --usage-file: "
            "Hermes 0.19 writes usage reports only on its native one-shot path, "
            "while NemoClaw routes this form through chat --query to append to "
            "the selected or most recent session. Run the resumed turn without "
            "--usage-file.",
            file=sys.stderr,
        )
        return 2
    except _AmbiguousProviderModelSession:
        try:
            _require_upstream_cli_version(real_hermes, adapter["upstream_cli_version"])
        except _CliAdapterError as exc:
            return _report_cli_adapter_error(exc)
        print(
            "[COMPATIBILITY] Refusing provider/model translation after an "
            "ambiguous session name. Pass a multi-word --resume or --continue "
            "session name as one quoted argument.",
            file=sys.stderr,
        )
        return 2
    except _CliAdapterError as exc:
        return _report_cli_adapter_error(exc)
    try:
        os.execv(real_hermes, [real_hermes, *exec_argv])
    except OSError as exc:
        print(
            f"[SECURITY] Refusing to run hermes: failed to exec Hermes binary at {real_hermes}: {exc}",
            file=sys.stderr,
        )
        return 126
    return 126


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
