#!/usr/bin/python3 -I
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Wrapper installed at /usr/local/bin/hermes that enforces the runtime
# environment secret boundary for `hermes gateway` (NVIDIA/NemoClaw#4975) and
# masks credential-shaped values in `hermes config show` output.
#
# Why a Python wrapper, not a bash one:
#   - Python 3 invoked with `-I` (isolated mode) ignores PYTHONPATH, PYTHONHOME,
#     user site-packages, and other env-driven startup hooks. It has no
#     equivalent of bash's `BASH_ENV`/`ENV` mechanism that would let a hostile
#     runtime environment source attacker-controlled code before our logic
#     runs. Combined with the absolute shebang (`#!/usr/bin/python3 -I`),
#     the wrapper entrypoint is independent of caller-controlled startup
#     files.
#   - The wrapper resolves the real binary, the validator script, and the
#     trusted python3 interpreter from fixed absolute paths, never from the
#     environment, so an untrusted PATH cannot redirect any of them. The dev
#     fallback resolves against this script's own directory so a checkout
#     works without an install, matching the resolution that
#     `agents/hermes/start.sh` uses for `_HERMES_BOUNDARY_VALIDATOR`.
#
# Source-of-truth note for the `config show` masking layer (reported leak is
# tracked in NVIDIA/NemoClaw#5981; the runtime-env guard for `hermes gateway`
# was added in NVIDIA/NemoClaw#4975):
#   - Invalid state: the upstream Hermes CLI prints inline provider `api_key`
#     values verbatim when asked to render the resolved configuration, so a
#     user running `hermes config show` sees an `sk-`-prefixed string that
#     looks like a real credential.
#   - Value being masked: for configs generated by
#     `agents/hermes/config/hermes-config.ts:buildHermesConfig`, the literal
#     placeholder `sk-OPENSHELL-PROXY-REWRITE` is hard-coded for the `model`,
#     `providers`, and `custom_providers` `api_key` fields; the user's real
#     provider credential is never serialised into the rendered config
#     (requests are rewritten at the OpenShell egress boundary). The masker
#     also unconditionally redacts any `api_key`-shaped field — including a
#     real value supplied via the seed-routing fallback in
#     `agents/hermes/seed-dashboard-config.py:_route_api_key` — so the
#     post-mask user-visible stream is safe in every case.
#   - Source-fix constraint: removing the inline `api_key` would require
#     either Hermes CLI native env-var reference support (an upstream
#     change) or a redesigned dashboard/runtime contract that no longer
#     needs an `sk-`-prefixed placeholder in the rendered config.
#   - Regression test: `test/hermes-gateway-wrapper.test.ts` —
#     `masks every api_key emitted by buildHermesConfig ...` derives a
#     fixture from `buildHermesConfig()` and asserts no raw placeholder
#     survives in stdout for `config show`.
#   - Removal condition: delete the `config show` branch when Hermes CLI
#     redacts credential-shaped fields natively or `buildHermesConfig` stops
#     emitting an inline `api_key` value.
#
# Source-of-truth note for the `_translate_resumed_oneshot` parser
# differential risk (NVIDIA/NemoClaw#5254):
#   - Invalid state: upstream Hermes currently accepts top-level resumed or
#     continued one-shot flags but persists the turn in a new session instead
#     of appending to the selected session; the wrapper therefore parses a
#     small allowlist of Hermes argv forms so it can route only those affected
#     invocations through Hermes' native `chat --query` append path.
#   - Risk accepted: upstream Hermes flag parsing may diverge from this
#     wrapper's allowlist. The wrapper fails closed to unchanged passthrough on
#     ambiguity, so the safe fallback is preserving Hermes' native behavior,
#     but that may lose the resume/continue append workaround until the
#     allowlist is updated.
#   - Mitigations: the Dockerfile performs build-time AST validation of the
#     wrapper flag constants, probes the pinned `hermes --help` surfaces, and
#     the wrapper suite covers routed forms plus fail-closed cases with 20+
#     unit tests.
#   - Tracking: keep monitoring upstream Hermes flag stability while this
#     localized compatibility layer exists.
#   - Removal condition: delete this translation when Hermes natively appends
#     top-level resumed or continued one-shot turns to the selected session.
#
# Scope of the masker: structured key-labelled secret fields (api_key,
# api_secret, access_token, auth_token, client_secret, secret_key, secret,
# token, password, bearer, authorization, credential — including
# hyphen/underscore/camelCase variants) in Python-dict, JSON, YAML key:value,
# env-style key=value, and YAML block-scalar shapes (`|`, `|-`, `|+`, `|2`,
# `|2-`, `|2+`, `|-2`, and folded `>` equivalents); plus, as defence in depth,
# every free-form `sk-`-prefixed token of length >= 8. Non-`sk-` token families
# in free prose are not redacted — that is the upstream Hermes CLI's
# responsibility.
#
# The same gateway runtime-env guard also runs in the nemoclaw-start
# entrypoint (`agents/hermes/start.sh:validate_hermes_runtime_env_secret_boundary`)
# and in the host-side gateway recovery path, but a direct
# `docker exec ... hermes gateway run` invocation bypasses the entrypoint
# entirely, so it would start the gateway with raw secret-shaped env vars
# (e.g. `SLACK_BOT_TOKEN=xoxb-real-...`). Wrapping the binary closes that
# bypass: every path that launches the gateway now passes through the same
# single-source-of-truth validator before the port is bound.
#
# Only a small set of top-level commands are intercepted; all other hermes
# subcommands (dashboard, --version, ...) pass straight through unchanged.

import os
import subprocess
import sys
import tempfile

_INSTALLED_REAL = "/usr/local/bin/hermes.real"
_INSTALLED_GUARD = "/usr/local/lib/nemoclaw/validate-hermes-env-secret-boundary.py"
# The Dockerfile installs the validator under the hermes-prefixed name even
# though the repository source stays at `validate-env-secret-boundary.py`.
# Mirror the same dev-fallback `start.sh` uses so an ad-hoc bash invocation
# over a checkout still finds the guard.
_GUARD_DEV_FILENAME = "validate-env-secret-boundary.py"
# Trusted absolute paths for the python3 interpreter, ordered most-preferred
# first. The resolver returns the first executable match (first-wins); the
# same priority is mirrored by `agents/hermes/start.sh:resolve_trusted_python3`
# so both entry points pick the same interpreter when several are present.
# Venv first matches the security principle of preferring the most controlled
# environment; fall back to system python3 when the sandbox image has no venv
# yet.
_TRUSTED_PYTHON3 = (
    "/opt/hermes/.venv/bin/python3",
    "/usr/local/bin/python3",
    "/usr/bin/python3",
)


def _self_dir() -> str:
    return os.path.dirname(os.path.realpath(__file__))


def _resolve_real_hermes() -> str:
    if os.access(_INSTALLED_REAL, os.X_OK):
        return _INSTALLED_REAL
    return os.path.join(_self_dir(), "hermes.real")


def _resolve_guard() -> str:
    if os.path.isfile(_INSTALLED_GUARD):
        return _INSTALLED_GUARD
    return os.path.join(_self_dir(), _GUARD_DEV_FILENAME)


def _resolve_trusted_python3() -> str | None:
    for candidate in _TRUSTED_PYTHON3:
        if os.access(candidate, os.X_OK):
            return candidate
    return None


_MASKER_STDERR_ALLOWED_PREFIX = "[SECURITY]"
_MASKER_STDERR_MAX_BYTES = 10 * 1024 * 1024


def _read_masker_stderr(file_obj, stream_name: str) -> tuple[bytes, bool]:
    file_obj.seek(0)
    raw = file_obj.read(_MASKER_STDERR_MAX_BYTES + 1)
    if len(raw) > _MASKER_STDERR_MAX_BYTES:
        print(
            f"[SECURITY] Refusing hermes config show: output masker stderr exceeded {_MASKER_STDERR_MAX_BYTES} bytes ({stream_name})",
            file=sys.stderr,
        )
        return raw[:_MASKER_STDERR_MAX_BYTES], True
    return raw, False


def _forward_sanitised_masker_stderr(raw: bytes, fallback: str) -> None:
    # Only forward lines that match the documented `[SECURITY] ...` prefix from
    # the masker itself. Anything else (Python tracebacks, import errors, OOM
    # messages) is dropped and replaced with a generic notice so internal file
    # paths and stack frames cannot leak through the user's terminal on an
    # unhandled exception.
    text = raw.decode("utf-8", errors="replace")
    safe_lines = [
        line for line in text.splitlines() if line.startswith(_MASKER_STDERR_ALLOWED_PREFIX)
    ]
    if safe_lines:
        sys.stderr.write("\n".join(safe_lines) + "\n")
    else:
        sys.stderr.write(fallback + "\n")


def _run_config_show(real_hermes: str, guard_path: str, argv: list[str]) -> int:
    python3 = _resolve_trusted_python3()
    if python3 is None:
        print(
            "[SECURITY] Refusing hermes config show: no python3 at a trusted absolute path to run the output masker",
            file=sys.stderr,
        )
        return 127
    # The masker reads its stdin and writes the redacted stream to its own
    # stdout. We spawn one masker per Hermes stream and pipe Hermes' raw
    # bytes through it. Closing the parent's reference to each masker's
    # stdin pipe (after `real_hermes` inherits the FD) makes the masker see
    # EOF when Hermes finishes writing. The masker itself buffers in
    # memory and only writes on success, so a mid-stream crash never
    # produces a partial secret on either stream. Each masker's own stderr
    # is captured to a temporary file so we can filter it before forwarding — a
    # raw `stderr=sys.stderr.fileno()` would leak Python tracebacks on an
    # unhandled exception, while a pipe could deadlock if a masker writes a
    # large diagnostic before the parent drains it.
    masker_argv = [python3, "-I", guard_path, "mask-config-output"]
    with (
        tempfile.TemporaryFile() as stdout_masker_stderr_file,
        tempfile.TemporaryFile() as stderr_masker_stderr_file,
    ):
        masker_stdout = subprocess.Popen(
            masker_argv,
            stdin=subprocess.PIPE,
            stdout=sys.stdout.fileno(),
            stderr=stdout_masker_stderr_file,
        )
        masker_stderr = subprocess.Popen(
            masker_argv,
            stdin=subprocess.PIPE,
            stdout=sys.stderr.fileno(),
            stderr=stderr_masker_stderr_file,
        )
        try:
            proc = subprocess.Popen(
                [real_hermes, *argv],
                stdout=masker_stdout.stdin,
                stderr=masker_stderr.stdin,
            )
        except OSError as exc:
            if masker_stdout.stdin is not None:
                masker_stdout.stdin.close()
            if masker_stderr.stdin is not None:
                masker_stderr.stdin.close()
            for masker in (masker_stdout, masker_stderr):
                try:
                    masker.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    masker.terminate()
                    masker.wait(timeout=5)
            print(
                "[SECURITY] Refusing hermes config show: failed to exec Hermes "
                f"({exc.__class__.__name__})",
                file=sys.stderr,
            )
            return 126
        else:
            if masker_stdout.stdin is not None:
                masker_stdout.stdin.close()
            if masker_stderr.stdin is not None:
                masker_stderr.stdin.close()
        proc.wait()
        masker_stdout.wait()
        masker_stderr.wait()
        stdout_masker_stderr, stdout_masker_stderr_too_large = _read_masker_stderr(
            stdout_masker_stderr_file,
            "stdout",
        )
        stderr_masker_stderr, stderr_masker_stderr_too_large = _read_masker_stderr(
            stderr_masker_stderr_file,
            "stderr",
        )
    if stdout_masker_stderr_too_large or stderr_masker_stderr_too_large:
        return 1
    if masker_stdout.returncode != 0:
        _forward_sanitised_masker_stderr(
            stdout_masker_stderr,
            "[SECURITY] Refusing hermes config show: output masker failed (stdout)",
        )
        return masker_stdout.returncode
    if masker_stderr.returncode != 0:
        _forward_sanitised_masker_stderr(
            stderr_masker_stderr,
            "[SECURITY] Refusing hermes config show: output masker failed (stderr)",
        )
        return masker_stderr.returncode
    return proc.returncode


def _run_gateway_guard(guard_path: str) -> int:
    python3 = _resolve_trusted_python3()
    if python3 is None:
        print(
            "[SECURITY] Refusing hermes gateway: no python3 at a trusted absolute path to run the secret-boundary guard",
            file=sys.stderr,
        )
        return 127
    return subprocess.call([python3, "-I", guard_path, "runtime-env"])


_VALUE_FLAGS = {
    "-m": "--model",
    "--model": "--model",
    "--provider": "--provider",
    "-t": "--toolsets",
    "--toolsets": "--toolsets",
    "-s": "--skills",
    "--skills": "--skills",
    "-r": "--resume",
    "--resume": "--resume",
}
# Keep this allowlist aligned with the top-level flags accepted by the pinned
# Hermes Agent CLI in agents/hermes/Dockerfile.base (HERMES_VERSION=v2026.6.19,
# HERMES_SEMVER=0.17.0) and agents/hermes/manifest.yaml (expected_version
# "0.17.0"). Unknown flags deliberately fail closed by passing the original argv
# through to upstream Hermes.
_BOOLEAN_FLAGS = {
    "--worktree",
    "-w",
    "--accept-hooks",
    "--yolo",
    "--pass-session-id",
    "--ignore-user-config",
    "--ignore-rules",
}


def _split_flag_value(arg: str) -> tuple[str, str] | None:
    if not arg.startswith("--") or "=" not in arg:
        return None
    name, value = arg.split("=", 1)
    return name, value


def _translate_resumed_oneshot(argv: list[str]) -> list[str] | None:
    """Route resumed oneshot invocations through Hermes' native chat resume path.

    Upstream Hermes handles top-level `-z/--oneshot` before the normal
    `--resume`/`--continue` chat shortcut. In affected versions the resumed
    session is available as context, but the one-shot turn is persisted under a
    newly generated session id. The `chat --query --quiet --resume ...` path is
    the native non-interactive route that appends to the selected session, so
    translate only the composed top-level form and leave plain one-shot
    invocations untouched.

    NemoClaw owns this installed wrapper, not the prebuilt Hermes Agent binary
    inside the sandbox base image, so the wrapper is the smallest compatibility
    boundary available here. NemoClaw #5254 is the local removal tracker; avoid
    adding unofficial upstream repository links here per the repo's no external
    project links rule. Delete this translation once the pinned Hermes runtime
    natively appends top-level `--resume/-c` plus `-z/--oneshot` turns to the
    selected session without creating a fresh session id. Until then, wrapper
    argv tests cover the routed form and the fail-closed cases; live sandbox
    validation verifies the persisted `sessions list/export` behavior.

    Preserve approval-related user intent instead of inferring it here:
    `--yolo` and `--accept-hooks` are forwarded only when the original argv
    included those flags. The underlying Hermes one-shot policy can change
    across releases, so this compatibility layer avoids broadening approvals.
    """
    oneshot_prompt: str | None = None
    resume_args: list[str] = []
    passthrough: list[str] = []
    saw_resume = False
    saw_continue = False
    saw_oneshot = False

    i = 0
    while i < len(argv):
        arg = argv[i]

        if arg == "--":
            return None

        split = _split_flag_value(arg)
        if split is not None:
            name, value = split
            if name == "--oneshot":
                if saw_oneshot:
                    return None
                saw_oneshot = True
                oneshot_prompt = value
            elif name == "--continue":
                if not value:
                    return None
                if saw_resume or saw_continue:
                    return None
                saw_continue = True
                resume_args.extend(["--continue", value])
            elif name in _VALUE_FLAGS:
                canonical = _VALUE_FLAGS[name]
                if canonical == "--resume":
                    if not value:
                        return None
                    if saw_resume or saw_continue:
                        return None
                    saw_resume = True
                    resume_args.extend([canonical, value])
                else:
                    passthrough.extend([canonical, value])
            else:
                return None
            i += 1
            continue

        if arg in ("-z", "--oneshot"):
            if i + 1 >= len(argv) or argv[i + 1].startswith("-"):
                return None
            if saw_oneshot:
                return None
            saw_oneshot = True
            oneshot_prompt = argv[i + 1]
            i += 2
            continue

        if arg in _VALUE_FLAGS:
            if i + 1 >= len(argv) or argv[i + 1].startswith("-"):
                return None
            canonical = _VALUE_FLAGS[arg]
            value = argv[i + 1]
            if not value:
                return None
            if canonical == "--resume":
                if saw_resume or saw_continue:
                    return None
                saw_resume = True
                resume_args.extend([canonical, value])
            else:
                passthrough.extend([canonical, value])
            i += 2
            continue

        if arg in ("-c", "--continue"):
            if saw_resume or saw_continue:
                return None
            if i + 1 >= len(argv) or argv[i + 1].startswith("-"):
                return None
            value = argv[i + 1]
            if not value:
                return None
            saw_continue = True
            resume_args.append("--continue")
            resume_args.append(value)
            i += 2
            continue

        if arg in _BOOLEAN_FLAGS:
            passthrough.append(arg)
            i += 1
            continue

        # A positional command means this is not the top-level one-shot form.
        return None

    if not oneshot_prompt or not (saw_resume or saw_continue):
        return None

    translated = ["chat", "--query", oneshot_prompt, "--quiet"]
    translated.extend(resume_args)
    translated.extend(passthrough)
    return translated


def main(argv: list[str]) -> int:
    real_hermes = _resolve_real_hermes()
    guard_path = _resolve_guard()
    if argv[:2] == ["config", "show"]:
        return _run_config_show(real_hermes, guard_path, argv)
    if argv[:1] == ["gateway"]:
        rc = _run_gateway_guard(guard_path)
        if rc != 0:
            return rc
    translated = _translate_resumed_oneshot(argv)
    if translated is not None:
        exec_argv = translated
    else:
        exec_argv = argv
    try:
        os.execv(real_hermes, [real_hermes, *exec_argv])
    except OSError as exc:
        print(
            f"[SECURITY] Refusing to run hermes: failed to exec Hermes binary at {real_hermes}: {exc}",
            file=sys.stderr,
        )
        return 126
    return 126


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
