// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const DEEPAGENTS_MCP_MAX_SERVERS = 64;

export const DEEPAGENTS_STRICT_JSON_HELPERS = [
  "def reject_duplicate_keys(pairs):",
  "    result = {}",
  "    for key, value in pairs:",
  "        if key in result:",
  "            raise ValueError(f'duplicate JSON key: {key}')",
  "        result[key] = value",
  "    return result",
  "def reject_non_json_constant(value):",
  "    raise ValueError(f'non-JSON numeric constant: {value}')",
  "def strict_json_loads(raw):",
  "    return json.loads(raw, object_pairs_hook=reject_duplicate_keys, parse_constant=reject_non_json_constant)",
];

export const DEEPAGENTS_MANAGED_PROJECTION_READ_HELPERS = [
  "MANAGED_MCP_MAX_BYTES = 262144",
  "def managed_fingerprint(metadata):",
  "    return (metadata.st_dev, metadata.st_ino, metadata.st_size, metadata.st_mtime_ns, metadata.st_ctime_ns, metadata.st_mode, metadata.st_nlink, metadata.st_uid)",
  "def managed_path_identity(path):",
  "    try:",
  "        return managed_fingerprint(os.stat(path, follow_symlinks=False))",
  "    except FileNotFoundError:",
  "        return None",
  "def assert_managed_source_stable(path, identity):",
  "    current = managed_path_identity(path)",
  "    if identity is None:",
  "        if current is not None:",
  "            raise ValueError('managed MCP projection appeared during mutation')",
  "        return",
  "    if current != identity:",
  "        raise ValueError('managed MCP projection changed before mutation')",
  "def validate_managed_descriptor_path(path, descriptor):",
  "    opened = os.fstat(descriptor)",
  "    linked = os.stat(path, follow_symlinks=False)",
  "    safe = (stat.S_ISREG(opened.st_mode) and opened.st_uid == os.getuid() and stat.S_IMODE(opened.st_mode) == 0o600 and opened.st_nlink == 1 and (opened.st_dev, opened.st_ino) == (linked.st_dev, linked.st_ino))",
  "    if not safe:",
  "        raise ValueError('managed MCP projection has unsafe ownership, mode, type, links, or path identity')",
  "    return managed_fingerprint(opened)",
  "def open_managed_projection(path, writable=False):",
  "    access = os.O_RDWR if writable else os.O_RDONLY",
  "    flags = access | os.O_CLOEXEC | os.O_NONBLOCK | os.O_NOFOLLOW",
  "    try:",
  "        descriptor = os.open(path, flags)",
  "    except FileNotFoundError:",
  "        assert_managed_source_stable(path, None)",
  "        return b'', None, None",
  "    try:",
  "        before = os.fstat(descriptor)",
  "        validate_managed_descriptor_path(path, descriptor)",
  "        if before.st_size < 0 or before.st_size > MANAGED_MCP_MAX_BYTES:",
  "            raise ValueError('managed MCP projection has invalid size')",
  "        chunks = []",
  "        remaining = before.st_size",
  "        while remaining:",
  "            chunk = os.read(descriptor, remaining)",
  "            if not chunk:",
  "                break",
  "            chunks.append(chunk)",
  "            remaining -= len(chunk)",
  "        after = os.fstat(descriptor)",
  "        linked_after = os.stat(path, follow_symlinks=False)",
  "        stable = (managed_fingerprint(before) == managed_fingerprint(after) and managed_fingerprint(after) == managed_fingerprint(linked_after))",
  "        if remaining or not stable:",
  "            raise ValueError('managed MCP projection changed while reading')",
  "        return b''.join(chunks), managed_fingerprint(after), descriptor",
  "    except Exception:",
  "        os.close(descriptor)",
  "        raise",
  "def decode_managed_projection(raw):",
  "    return strict_json_loads(raw.decode('utf-8')) if raw else {}",
  "def close_managed_projection_descriptor(descriptor):",
  "    if descriptor is None:",
  "        return",
  "    try:",
  "        os.close(descriptor)",
  "    except OSError:",
  "        pass",
  "def load_managed_projection_for_update(path):",
  "    raw, identity, descriptor = open_managed_projection(path, True)",
  "    try:",
  "        return decode_managed_projection(raw), identity, descriptor",
  "    except Exception:",
  "        close_managed_projection_descriptor(descriptor)",
  "        raise",
  "def read_managed_projection(path):",
  "    raw, identity, descriptor = open_managed_projection(path)",
  "    try:",
  "        return decode_managed_projection(raw), identity",
  "    finally:",
  "        close_managed_projection_descriptor(descriptor)",
];

export const DEEPAGENTS_MANAGED_PROJECTION_MUTATION_HELPERS = [
  "def managed_projection_bytes(value):",
  "    payload = (json.dumps(value, indent=2, sort_keys=True) + '\\n').encode('utf-8')",
  "    if not payload or len(payload) > MANAGED_MCP_MAX_BYTES:",
  "        raise ValueError('managed MCP projection has invalid rendered size')",
  "    return payload",
  "def rewrite_managed_projection(path, value, identity, descriptor):",
  "    if identity is None or descriptor is None:",
  "        raise ValueError('managed MCP projection descriptor is unavailable')",
  "    assert_managed_source_stable(path, identity)",
  "    payload = managed_projection_bytes(value)",
  "    os.lseek(descriptor, 0, os.SEEK_SET)",
  "    os.ftruncate(descriptor, 0)",
  "    offset = 0",
  "    while offset < len(payload):",
  "        written = os.write(descriptor, payload[offset:])",
  "        if written <= 0:",
  "            raise OSError('managed MCP projection write made no progress')",
  "        offset += written",
  "    os.fsync(descriptor)",
  "    os.lseek(descriptor, 0, os.SEEK_SET)",
  "    persisted = os.read(descriptor, len(payload) + 1)",
  "    if persisted != payload or os.fstat(descriptor).st_size != len(payload):",
  "        raise ValueError('managed MCP projection verification failed')",
  "    validate_managed_descriptor_path(path, descriptor)",
  "def publish_absent_managed_projection(path, value):",
  "    assert_managed_source_stable(path, None)",
  "    payload = managed_projection_bytes(value)",
  "    tmp_fd, tmp_name = tempfile.mkstemp(prefix='.nemoclaw-mcp.', dir=path.parent)",
  "    try:",
  "        os.fchmod(tmp_fd, 0o600)",
  "        with os.fdopen(tmp_fd, 'wb') as tmp_file:",
  "            tmp_file.write(payload)",
  "            tmp_file.flush()",
  "            os.fsync(tmp_file.fileno())",
  "        try:",
  "            os.link(tmp_name, path, follow_symlinks=False)",
  "        except FileExistsError as exc:",
  "            raise ValueError('managed MCP projection appeared during publication') from exc",
  "        os.unlink(tmp_name)",
  "    finally:",
  "        try:",
  "            os.unlink(tmp_name)",
  "        except FileNotFoundError:",
  "            pass",
  "    persisted, _ = read_managed_projection(path)",
  "    if persisted != value:",
  "        raise ValueError('managed MCP projection verification failed')",
  "def write_managed_projection(path, value, identity, descriptor):",
  "    if identity is None:",
  "        if descriptor is not None:",
  "            raise ValueError('unexpected managed MCP projection descriptor')",
  "        publish_absent_managed_projection(path, value)",
  "    else:",
  "        try:",
  "            rewrite_managed_projection(path, value, identity, descriptor)",
  "        finally:",
  "            close_managed_projection_descriptor(descriptor)",
];

export const DEEPAGENTS_MANAGED_PROJECTION_HELPERS = [
  ...DEEPAGENTS_MANAGED_PROJECTION_READ_HELPERS,
  ...DEEPAGENTS_MANAGED_PROJECTION_MUTATION_HELPERS,
];
