// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { afterEach, describe, expect, it, vi } from "vitest";

import * as sandboxState from "../state/sandbox";
import { finalizeCreatedSandbox } from "./created-sandbox-finalization";
import { getDcodeSelectionDrift } from "./dcode-selection-drift";

const fixtures: string[] = [];

afterEach(() => {
  delete process.env.NEMOCLAW_OPENSHELL_BIN;
  for (const fixture of fixtures.splice(0)) fs.rmSync(fixture, { recursive: true, force: true });
  vi.restoreAllMocks();
});

function executable(file: string, contents: string): void {
  fs.writeFileSync(file, contents, { mode: 0o755 });
}

function makeRestoreFixture(): {
  backupPath: string;
  currentPath: string;
  oldPath: string;
} {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "nemoclaw-dcode-finalize-"));
  fixtures.push(root);
  const bin = path.join(root, "bin");
  const backupPath = path.join(root, "backup");
  const liveDir = path.join(root, "live", ".deepagents");
  const currentPath = path.join(liveDir, "config.toml");
  const oldPath = process.env.PATH ?? "";
  fs.mkdirSync(bin, { recursive: true });
  fs.mkdirSync(backupPath);
  fs.mkdirSync(liveDir, { recursive: true });

  fs.writeFileSync(
    path.join(backupPath, "rebuild-manifest.json"),
    JSON.stringify({
      version: 1,
      sandboxName: "dcode",
      timestamp: "2026-07-06T00:00:00.000Z",
      agentType: "langchain-deepagents-code",
      agentVersion: "0.1.0",
      expectedVersion: "0.1.0",
      stateDirs: [],
      backedUpDirs: [],
      stateFiles: [{ path: "config.toml", strategy: "copy" }],
      dir: "/sandbox/.deepagents",
      backupPath,
      blueprintDigest: null,
    }),
  );
  fs.writeFileSync(
    path.join(backupPath, "config.toml"),
    [
      "[models]",
      'default = "openai:old-model"',
      "",
      "[update]",
      "check = true",
      "auto_update = true",
      "",
      "[agents]",
      'default = "reviewer"',
      "",
      "[ui]",
      'theme = "dark"',
      "show_scrollbar = true",
      "",
    ].join("\n"),
  );
  fs.writeFileSync(
    currentPath,
    [
      "# Generated by NemoClaw. This file contains no provider secrets.",
      "# NemoClaw provider route: inference; upstream provider: nvidia-prod; API: openai-completions.",
      "",
      "[models]",
      'default = "openai:new-model"',
      "",
      "[models.providers.openai]",
      'models = ["new-model"]',
      'api_key_env = "DEEPAGENTS_CODE_OPENAI_API_KEY"',
      'base_url = "https://inference.local/v1"',
      "enabled = true",
      "",
      "[update]",
      "check = false",
      "auto_update = false",
      "",
    ].join("\n"),
  );

  const pythonResult = spawnSync("python3", ["-c", "import sys; print(sys.executable)"], {
    encoding: "utf8",
  });
  expect(pythonResult.status, `Python 3 is required: ${pythonResult.stderr}`).toBe(0);
  expect(pythonResult.stdout.trim(), "Python 3 executable path is required").not.toBe("");
  const hostPython = pythonResult.stdout.trim();
  const python = path.join(bin, "python3");
  executable(
    python,
    `#!${hostPython}
import json
import subprocess
import sys
import types

NODE_TOML_WRITER = r"""
const fs = require("node:fs");
const { stringify } = require("smol-toml");
const value = JSON.parse(fs.readFileSync(0, "utf8"));
process.stdout.write(stringify(value));
"""

def dumps(value):
    completed = subprocess.run(
        ["node", "-e", NODE_TOML_WRITER],
        input=json.dumps(value, allow_nan=False),
        capture_output=True,
        check=True,
        text=True,
    )
    return completed.stdout

tomli_w = types.ModuleType("tomli_w")
tomli_w.dumps = dumps
sys.modules["tomli_w"] = tomli_w

try:
    script_index = sys.argv.index("-c", 1) + 1
except ValueError:
    script_index = 1
script = sys.argv[script_index]
sys.argv = [sys.argv[0], *sys.argv[script_index + 1:]]
exec(script, {"__name__": "__main__"})
`,
  );
  const openshell = path.join(bin, "openshell");
  executable(
    openshell,
    '#!/usr/bin/env bash\nprintf "Host openshell-%s\\n  HostName 127.0.0.1\\n  User sandbox\\n" "${!#}"\n',
  );
  executable(
    path.join(bin, "ssh"),
    `#!/usr/bin/env node
const fs = require("node:fs");
const { spawnSync } = require("node:child_process");
const command = process.argv.at(-1)
  .replaceAll("/sandbox/.deepagents", ${JSON.stringify(liveDir)})
  .replace("/opt/venv/bin/python3", ${JSON.stringify(python)});
const result = spawnSync("bash", ["-c", command], { input: fs.readFileSync(0), stdio: ["pipe", "pipe", "pipe"] });
if (result.stdout) fs.writeSync(1, result.stdout);
if (result.stderr) fs.writeSync(2, result.stderr);
process.exit(result.status ?? 1);
`,
  );
  process.env.NEMOCLAW_OPENSHELL_BIN = openshell;
  process.env.PATH = `${bin}${path.delimiter}${oldPath}`;
  return { backupPath, currentPath, oldPath };
}

function identityFromConfig(config: string): string {
  const metadata = config.match(
    /^# NemoClaw provider route: ([^;]+); upstream provider: ([^;]+);/m,
  );
  const model = config.match(/^default = "([^"]+)"$/m)?.[1];
  const endpoint = config.match(/^base_url = "([^"]+)"$/m)?.[1];
  return [
    `Route:    ${metadata?.[1] ?? ""}`,
    `Provider: ${metadata?.[2] ?? ""}`,
    `Model:    ${model ?? ""}`,
    `Endpoint: ${endpoint ?? ""}`,
  ].join("\n");
}

describe("created DCode sandbox finalization", () => {
  it("merges stale backup preferences before live validation and registry publication (#6311)", () => {
    const fixture = makeRestoreFixture();
    const order: string[] = [];
    const registeredConfigs: string[] = [];
    try {
      finalizeCreatedSandbox(
        {
          sandboxName: "dcode",
          restoreBackupPath: fixture.backupPath,
          preUpgradeBackup: false,
          targetAgentType: "langchain-deepagents-code",
          validateManagedDcode: true,
          provider: "nvidia-prod",
          model: "new-model",
          preferredInferenceApi: null,
        },
        {
          discoverFreshOpenClawImagePluginInstalls: () => ({
            ok: true,
            extensionDirs: [],
            pluginInstalls: [],
          }),
          restoreRecreatedSandboxState: (name, backup, options) => {
            order.push("restore");
            expect(options.allowCustomImageWholeStateFileRestore).toBeUndefined();
            return sandboxState.restoreRecreatedSandboxState(name, backup, options);
          },
          getDcodeSelectionDrift: (name, provider, model, api) => {
            order.push("validate");
            return getDcodeSelectionDrift(name, provider, model, api, {
              runCaptureOpenshell: () =>
                identityFromConfig(fs.readFileSync(fixture.currentPath, "utf8")),
            });
          },
          register: () => {
            order.push("register");
            registeredConfigs.push(fs.readFileSync(fixture.currentPath, "utf8"));
          },
          note: vi.fn(),
          error: vi.fn(),
          exitProcess: (code): never => {
            throw new Error(`exit ${code}`);
          },
        },
      );

      expect(order).toEqual(["restore", "validate", "register"]);
      expect(registeredConfigs[0]).toContain('default = "openai:new-model"');
      expect(registeredConfigs[0]).not.toContain("old-model");
      expect(registeredConfigs[0]).not.toContain("[agents]");
      expect(registeredConfigs[0]).toContain("[ui]\nshow_scrollbar = true");
      expect(registeredConfigs[0]).not.toContain('theme = "dark"');
    } finally {
      process.env.PATH = fixture.oldPath;
    }
  });

  it("does not publish registry metadata when live validation fails (#6311)", () => {
    const register = vi.fn();
    const error = vi.fn();
    expect(() =>
      finalizeCreatedSandbox(
        {
          sandboxName: "dcode",
          restoreBackupPath: null,
          preUpgradeBackup: false,
          targetAgentType: "langchain-deepagents-code",
          validateManagedDcode: true,
          provider: "nvidia-prod",
          model: "new-model",
          preferredInferenceApi: null,
        },
        {
          discoverFreshOpenClawImagePluginInstalls: vi.fn(),
          restoreRecreatedSandboxState: vi.fn(),
          getDcodeSelectionDrift: () => ({
            changed: true,
            providerChanged: false,
            modelChanged: true,
            existingProvider: "nvidia-prod",
            existingModel: "openai:old-model",
            unknown: false,
          }),
          register,
          note: vi.fn(),
          error,
          exitProcess: (code): never => {
            throw new Error(`exit ${code}`);
          },
        },
      ),
    ).toThrow("exit 1");
    expect(register).not.toHaveBeenCalled();
    expect(error).toHaveBeenCalledWith(expect.stringContaining("sandbox still exists"));
    expect(error).toHaveBeenCalledWith(expect.stringContaining("rebuild is unsafe"));
    expect(error).toHaveBeenCalledWith(expect.stringContaining('openshell sandbox delete "dcode"'));
    expect(error).toHaveBeenCalledWith(expect.stringContaining("nemoclaw onboard"));
  });

  it("warns but verifies and registers after a partial workspace restore (#6311)", () => {
    const fixture = makeRestoreFixture();
    const registeredConfigs: string[] = [];
    const error = vi.fn();
    try {
      finalizeCreatedSandbox(
        {
          sandboxName: "dcode",
          restoreBackupPath: fixture.backupPath,
          preUpgradeBackup: false,
          targetAgentType: "langchain-deepagents-code",
          validateManagedDcode: true,
          provider: "nvidia-prod",
          model: "new-model",
          preferredInferenceApi: null,
        },
        {
          discoverFreshOpenClawImagePluginInstalls: vi.fn(),
          restoreRecreatedSandboxState: (name, backup, options) => {
            const restored = sandboxState.restoreRecreatedSandboxState(name, backup, options);
            return { ...restored, success: false, failedDirs: ["skills"] };
          },
          getDcodeSelectionDrift: (name, provider, model, api) =>
            getDcodeSelectionDrift(name, provider, model, api, {
              runCaptureOpenshell: () =>
                identityFromConfig(fs.readFileSync(fixture.currentPath, "utf8")),
            }),
          register: () => {
            registeredConfigs.push(fs.readFileSync(fixture.currentPath, "utf8"));
          },
          note: vi.fn(),
          error,
          exitProcess: (code): never => {
            throw new Error(`exit ${code}`);
          },
        },
      );

      expect(error).toHaveBeenCalledWith(
        `  Warning: partial restore. Manual recovery: ${fixture.backupPath}`,
      );
      expect(registeredConfigs).toHaveLength(1);
      expect(registeredConfigs[0]).toContain('default = "openai:new-model"');
      expect(registeredConfigs[0]).not.toContain("old-model");
      expect(registeredConfigs[0]).toContain("[ui]\nshow_scrollbar = true");
      expect(registeredConfigs[0]).not.toContain('theme = "dark"');
    } finally {
      process.env.PATH = fixture.oldPath;
    }
  });

  it("keeps custom-image restores outside the managed config merge (#6311)", () => {
    const fixture = makeRestoreFixture();
    const registeredConfigs: string[] = [];
    try {
      finalizeCreatedSandbox(
        {
          sandboxName: "custom-dcode",
          restoreBackupPath: fixture.backupPath,
          preUpgradeBackup: false,
          targetAgentType: "langchain-deepagents-code",
          customImage: true,
          validateManagedDcode: false,
          provider: "custom-provider",
          model: "custom-model",
          preferredInferenceApi: null,
        },
        {
          discoverFreshOpenClawImagePluginInstalls: vi.fn(),
          restoreRecreatedSandboxState: (name, backup, options) => {
            expect(options.allowCustomImageWholeStateFileRestore).toBe(true);
            return sandboxState.restoreRecreatedSandboxState(name, backup, options);
          },
          getDcodeSelectionDrift: vi.fn(),
          register: () => registeredConfigs.push(fs.readFileSync(fixture.currentPath, "utf8")),
          note: vi.fn(),
          error: vi.fn(),
          exitProcess: (code): never => {
            throw new Error(`exit ${code}`);
          },
        },
      );

      expect(registeredConfigs).toHaveLength(1);
      expect(registeredConfigs[0]).toContain('default = "openai:old-model"');
      expect(registeredConfigs[0]).toContain("[agents]");
      expect(registeredConfigs[0]).toContain('theme = "dark"');
      expect(registeredConfigs[0]).not.toContain("new-model");
    } finally {
      process.env.PATH = fixture.oldPath;
    }
  });
});

describe("created OpenClaw sandbox finalization", () => {
  const pluginInstalls = [
    {
      id: "weather",
      installPath: "/sandbox/.openclaw/extensions/weather",
      loadPaths: [],
    },
  ];

  it("skips image-plugin discovery for a managed OpenClaw image", () => {
    const discoverFreshOpenClawImagePluginInstalls = vi.fn();
    const register = vi.fn();

    finalizeCreatedSandbox(
      {
        sandboxName: "openclaw",
        restoreBackupPath: null,
        preUpgradeBackup: false,
        targetAgentType: "openclaw",
        validateManagedDcode: false,
        provider: "compatible-endpoint",
        model: "demo",
        preferredInferenceApi: "openai-completions",
      },
      {
        discoverFreshOpenClawImagePluginInstalls,
        restoreRecreatedSandboxState: vi.fn(),
        getDcodeSelectionDrift: vi.fn(),
        register,
        note: vi.fn(),
        error: vi.fn(),
        exitProcess: (code) => {
          throw new Error(`unexpected exit ${code}`);
        },
      },
    );

    expect(discoverFreshOpenClawImagePluginInstalls).not.toHaveBeenCalled();
    expect(register).toHaveBeenCalledWith(undefined);
  });

  it("captures and registers a fresh image plugin baseline without a restore", () => {
    const order: string[] = [];
    const restoreRecreatedSandboxState = vi.fn();
    const register = vi.fn(() => order.push("register"));

    finalizeCreatedSandbox(
      {
        sandboxName: "openclaw",
        restoreBackupPath: null,
        preUpgradeBackup: false,
        targetAgentType: "openclaw",
        discoverOpenClawImagePluginInstalls: true,
        validateManagedDcode: false,
        provider: "compatible-endpoint",
        model: "demo",
        preferredInferenceApi: "openai-completions",
      },
      {
        discoverFreshOpenClawImagePluginInstalls: () => {
          order.push("discover");
          return { ok: true, extensionDirs: ["weather"], pluginInstalls };
        },
        restoreRecreatedSandboxState,
        getDcodeSelectionDrift: vi.fn(),
        register,
        note: vi.fn(),
        error: vi.fn(),
        exitProcess: (code): never => {
          throw new Error(`exit ${code}`);
        },
      },
    );

    expect(order).toEqual(["discover", "register"]);
    expect(restoreRecreatedSandboxState).not.toHaveBeenCalled();
    expect(register).toHaveBeenCalledWith(pluginInstalls);
  });

  it("preserves the fresh image plugin baseline across recreation before registration", () => {
    const order: string[] = [];
    const register = vi.fn(() => order.push("register"));
    const restoreRecreatedSandboxState = vi.fn(() => {
      order.push("restore");
      return {
        success: true,
        restoredDirs: ["extensions"],
        failedDirs: [],
        restoredFiles: ["openclaw.json"],
        failedFiles: [],
      };
    });

    finalizeCreatedSandbox(
      {
        sandboxName: "openclaw",
        restoreBackupPath: "/tmp/openclaw-backup",
        preUpgradeBackup: false,
        targetAgentType: "openclaw",
        discoverOpenClawImagePluginInstalls: true,
        validateManagedDcode: false,
        provider: "compatible-endpoint",
        model: "demo",
        preferredInferenceApi: "openai-completions",
      },
      {
        discoverFreshOpenClawImagePluginInstalls: () => {
          order.push("discover");
          return { ok: true, extensionDirs: ["weather"], pluginInstalls };
        },
        restoreRecreatedSandboxState,
        getDcodeSelectionDrift: vi.fn(),
        register,
        note: vi.fn(),
        error: vi.fn(),
        exitProcess: (code): never => {
          throw new Error(`exit ${code}`);
        },
      },
    );

    expect(order).toEqual(["discover", "restore", "register"]);
    expect(restoreRecreatedSandboxState).toHaveBeenCalledWith("openclaw", "/tmp/openclaw-backup", {
      targetAgentType: "openclaw",
      freshOpenClawImagePluginInstalls: pluginInstalls,
    });
    expect(register).toHaveBeenCalledWith(pluginInstalls);
  });

  it("defers managed restore before unregistered target authority can be bound", () => {
    const register = vi.fn();
    const error = vi.fn();

    expect(() =>
      finalizeCreatedSandbox(
        {
          sandboxName: "openclaw",
          restoreBackupPath: "/tmp/managed-openclaw-backup",
          preUpgradeBackup: false,
          targetAgentType: "openclaw",
          validateManagedDcode: false,
          provider: "compatible-endpoint",
          model: "demo",
          preferredInferenceApi: "openai-completions",
        },
        {
          discoverFreshOpenClawImagePluginInstalls: vi.fn(),
          restoreRecreatedSandboxState: () => ({
            success: false,
            restoredDirs: [],
            failedDirs: ["manifest"],
            restoredFiles: [],
            failedFiles: [],
            error: sandboxState.MANAGED_SNAPSHOT_RESTORE_AUTHORITY_ERROR,
          }),
          getDcodeSelectionDrift: vi.fn(),
          register,
          note: vi.fn(),
          error,
          exitProcess: (code): never => {
            throw new Error(`exit ${code}`);
          },
        },
      ),
    ).toThrow("exit 1");

    expect(register).not.toHaveBeenCalled();
    expect(error).toHaveBeenCalledWith(expect.stringContaining("restore is deferred"));
    expect(error).toHaveBeenCalledWith(
      "  State was not restored and registry metadata was not updated.",
    );
    expect(error).toHaveBeenCalledWith('    openshell sandbox delete "openclaw"');
    expect(error).toHaveBeenCalledWith("  Manual recovery: /tmp/managed-openclaw-backup");
  });

  it("fails closed before restore and registration when provenance discovery fails", () => {
    const restoreRecreatedSandboxState = vi.fn();
    const register = vi.fn();
    const error = vi.fn();

    expect(() =>
      finalizeCreatedSandbox(
        {
          sandboxName: "openclaw",
          restoreBackupPath: "/tmp/openclaw-backup",
          preUpgradeBackup: false,
          targetAgentType: "openclaw",
          discoverOpenClawImagePluginInstalls: true,
          validateManagedDcode: false,
          provider: "compatible-endpoint",
          model: "demo",
          preferredInferenceApi: "openai-completions",
        },
        {
          discoverFreshOpenClawImagePluginInstalls: () => ({
            ok: false,
            error: "registry unreadable",
          }),
          restoreRecreatedSandboxState,
          getDcodeSelectionDrift: vi.fn(),
          register,
          note: vi.fn(),
          error,
          exitProcess: (code): never => {
            throw new Error(`exit ${code}`);
          },
        },
      ),
    ).toThrow("exit 1");

    expect(restoreRecreatedSandboxState).not.toHaveBeenCalled();
    expect(register).not.toHaveBeenCalled();
    expect(error).toHaveBeenCalledWith(expect.stringContaining("registry unreadable"));
    expect(error).toHaveBeenCalledWith(
      "  State was not restored and registry metadata was not updated.",
    );
    expect(error).toHaveBeenCalledWith('    openshell sandbox delete "openclaw"');
    expect(error).toHaveBeenCalledWith(
      "  Then rerun the original `nemoclaw onboard --from <Dockerfile>` command.",
    );
    expect(error).toHaveBeenCalledWith("  Manual recovery: /tmp/openclaw-backup");
  });

  it("does not register after a marked backup provenance mismatch", () => {
    const register = vi.fn();
    const error = vi.fn();

    expect(() =>
      finalizeCreatedSandbox(
        {
          sandboxName: "openclaw",
          restoreBackupPath: "/tmp/openclaw-backup",
          preUpgradeBackup: false,
          targetAgentType: "openclaw",
          discoverOpenClawImagePluginInstalls: true,
          validateManagedDcode: false,
          provider: "compatible-endpoint",
          model: "demo",
          preferredInferenceApi: "openai-completions",
        },
        {
          discoverFreshOpenClawImagePluginInstalls: () => ({
            ok: true,
            extensionDirs: ["weather"],
            pluginInstalls,
          }),
          restoreRecreatedSandboxState: () => ({
            success: false,
            restoredDirs: [],
            failedDirs: ["manifest"],
            restoredFiles: [],
            failedFiles: [],
            error: sandboxState.OPENCLAW_IMAGE_PLUGIN_PROVENANCE_RESTORE_ERROR,
          }),
          getDcodeSelectionDrift: vi.fn(),
          register,
          note: vi.fn(),
          error,
          exitProcess: (code): never => {
            throw new Error(`exit ${code}`);
          },
        },
      ),
    ).toThrow("exit 1");

    expect(register).not.toHaveBeenCalled();
    expect(error).toHaveBeenCalledWith(expect.stringContaining("future rebuild would be unsafe"));
    expect(error).toHaveBeenCalledWith(
      expect.stringContaining(sandboxState.OPENCLAW_IMAGE_PLUGIN_PROVENANCE_RESTORE_ERROR),
    );
    expect(error).toHaveBeenCalledWith('    openshell sandbox delete "openclaw"');
    expect(error).toHaveBeenCalledWith(
      "  Then rerun the original `nemoclaw onboard --from <Dockerfile>` command.",
    );
    expect(error).toHaveBeenCalledWith("  Manual recovery: /tmp/openclaw-backup");
  });
});
