// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { describe, expect, it, vi } from "vitest";

import { detectSandboxFallbackDns, parseResolvConfNameservers } from "./docker-gpu-dns-fallback";

const RESOLV_CONF = "/etc/resolv.conf";
const SYSTEMD_RESOLV_CONF = "/run/systemd/resolve/resolv.conf";
const LOOPBACK_STUB = "nameserver 127.0.0.53\n";

function readSequence(...contents: Array<string | null>) {
  const readFile = vi.fn<(path: string) => string | null>();
  for (const content of contents) readFile.mockReturnValueOnce(content);
  return readFile;
}

describe("parseResolvConfNameservers", () => {
  it.each([
    [
      "parses loopback and direct nameservers across resolv.conf whitespace",
      "# generated\n  nameserver 127.0.0.53\n\tnameserver\t192.168.1.1\nsearch lan\n",
      ["127.0.0.53", "192.168.1.1"],
    ],
    [
      "ignores empty, malformed, and non-IP resolver lines",
      "\nsearch lan\nnameserver\nnameserver not-an-ip\nnameserver-alias 8.8.8.8\nnot-a-resolver 1.1.1.1\n",
      [],
    ],
  ])("%s (resolver parsing)", (_title, source, expected) => {
    expect(parseResolvConfNameservers(source)).toEqual(expected);
  });
});

describe("detectSandboxFallbackDns", () => {
  it("returns the systemd-resolved upstream when /etc/resolv.conf is loopback-only", () => {
    const files: Record<string, string> = {
      [RESOLV_CONF]: `${LOOPBACK_STUB}search lan\n`,
      [SYSTEMD_RESOLV_CONF]:
        "# Generated by systemd-resolved\nnameserver 8.8.8.8\nnameserver 1.1.1.1\n",
    };

    const readFile = vi.fn((path: string) => files[path] ?? null);
    expect(detectSandboxFallbackDns({ readFile })).toBe("8.8.8.8");
    expect(readFile.mock.calls.map(([path]) => path)).toEqual([RESOLV_CONF, SYSTEMD_RESOLV_CONF]);
  });

  it.each([
    ["direct resolver", ["nameserver 192.168.1.1\n"]],
    ["missing resolver", [null]],
    ["missing systemd upstream", [LOOPBACK_STUB, null]],
  ])("returns null without a loopback-only resolver and usable systemd upstream: %s", (_case, responses) => {
    expect(detectSandboxFallbackDns({ readFile: readSequence(...responses) })).toBeNull();
  });

  it.each([
    ["direct", "nameserver 192.168.1.1\n"],
    ["mixed", `${LOOPBACK_STUB}nameserver 10.0.0.2\n`],
  ])("does not read the upstream file for a %s resolver configuration", (_case, root) => {
    const readFile = readSequence(root);
    expect(detectSandboxFallbackDns({ readFile })).toBeNull();
    expect(readFile).toHaveBeenCalledTimes(1);
  });

  it.each([
    ["empty", [""]],
    ["missing", [null]],
    ["malformed", ["search lan\nnameserver\n"]],
    ["unreadable upstream", [LOOPBACK_STUB, null]],
  ])("returns null for %s resolver files", (_case, responses) => {
    const readFile = readSequence(...responses);
    expect(detectSandboxFallbackDns({ readFile })).toBeNull();
    expect(readFile).toHaveBeenCalledTimes(responses.length);
  });

  it.each([
    ["loopback-only", "nameserver 127.0.0.54\n"],
    ["malformed", "search lan\nnameserver\n"],
  ])("ignores %s upstream entries", (_case, upstream) => {
    expect(
      detectSandboxFallbackDns({ readFile: readSequence(LOOPBACK_STUB, upstream) }),
    ).toBeNull();
  });

  it.each([
    [
      "unspecified and multicast",
      "nameserver 0.0.0.0\nnameserver 224.0.0.1\nnameserver ::\nnameserver ff02::1\n",
      null,
    ],
    ["valid link-local", "nameserver 169.254.169.253\n", "169.254.169.253"],
  ])("rejects or preserves %s upstreams", (_case, upstream, expected) => {
    expect(detectSandboxFallbackDns({ readFile: readSequence(LOOPBACK_STUB, upstream) })).toBe(
      expected,
    );
  });

  it.each([
    [
      "accepts a private upstream because host resolver integrity is the trust boundary",
      LOOPBACK_STUB,
      "nameserver 10.20.30.53\n",
      "10.20.30.53",
    ],
    [
      // Docker cannot reliably reach an IPv6 upstream from the container path,
      // so this compatibility override ignores IPv6 and prefers the first
      // usable IPv4, regardless of resolver ordering (#7172).
      "prefers the first usable IPv4 over an earlier IPv6 upstream",
      LOOPBACK_STUB,
      "nameserver 2606:4700:4700::1111\nnameserver 169.254.169.253\n",
      "169.254.169.253",
    ],
    [
      // No usable IPv4 → return null and preserve Docker defaults rather than
      // injecting an unreachable IPv6 resolver (#7172).
      "returns null for an IPv6-only upstream list",
      "nameserver ::1\n",
      "nameserver 2001:4860:4860::8888\n",
      null,
    ],
  ])("%s (resolver selection)", (_title, root, upstream, expected) => {
    expect(detectSandboxFallbackDns({ readFile: readSequence(root, upstream) })).toBe(expected);
  });
});
