// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

const MINUTE_MS = 60_000;

export const SANDBOX_SURVIVAL_MARKER_PATHS = [
  "/sandbox/.openclaw/workspace/.survival-workspace-marker",
  "/sandbox/.openclaw/agents/main/sessions/.survival-session-marker",
  "/sandbox/.openclaw/memory/.survival-memory-marker",
] as const;

export const SANDBOX_SURVIVAL_NATIVE_READINESS = {
  attempts: 10,
  delayMs: 5_000,
  timeoutMs: 15_000,
} as const;
export const SANDBOX_SURVIVAL_LIFECYCLE_READINESS = {
  attempts: 10,
  delayMs: 5_000,
  timeoutMs: 15_000,
} as const;

export const SANDBOX_SURVIVAL_INSTALL_TIMEOUT_MS = 20 * MINUTE_MS;
export const SANDBOX_SURVIVAL_OPENSHELL_DELETE_TIMEOUT_MS = 2 * MINUTE_MS;
export const SANDBOX_SURVIVAL_GATEWAY_STOP_BUDGET_MS = 5 * MINUTE_MS;
export const SANDBOX_SURVIVAL_GATEWAY_DESTROY_TIMEOUT_MS = 2 * MINUTE_MS;
export const SANDBOX_SURVIVAL_PREREQUISITE_TIMEOUT_MS = 30_000;
export const SANDBOX_SURVIVAL_SANDBOX_LIFECYCLE_TIMEOUT_MS = 2 * MINUTE_MS;
export const SANDBOX_SURVIVAL_FINAL_DESTROY_TIMEOUT_MS = 2 * MINUTE_MS;
export const SANDBOX_SURVIVAL_POST_DESTROY_LIST_TIMEOUT_MS = MINUTE_MS;

export const SANDBOX_SURVIVAL_NATIVE_READINESS_POLLS = 2;
export const SANDBOX_SURVIVAL_LIFECYCLE_READINESS_POLLS = 1;
export const SANDBOX_SURVIVAL_EXEC_PROBES = 1;

export const SANDBOX_SURVIVAL_READINESS_WORST_CASE_MS =
  SANDBOX_SURVIVAL_EXEC_PROBES * SANDBOX_SURVIVAL_NATIVE_READINESS.timeoutMs +
  SANDBOX_SURVIVAL_NATIVE_READINESS_POLLS *
    SANDBOX_SURVIVAL_NATIVE_READINESS.attempts *
    (SANDBOX_SURVIVAL_NATIVE_READINESS.timeoutMs + SANDBOX_SURVIVAL_NATIVE_READINESS.delayMs) +
  SANDBOX_SURVIVAL_LIFECYCLE_READINESS_POLLS *
    SANDBOX_SURVIVAL_LIFECYCLE_READINESS.attempts *
    (SANDBOX_SURVIVAL_LIFECYCLE_READINESS.timeoutMs + SANDBOX_SURVIVAL_LIFECYCLE_READINESS.delayMs);

export const SANDBOX_SURVIVAL_PREPARATION_WORST_CASE_MS =
  SANDBOX_SURVIVAL_PREREQUISITE_TIMEOUT_MS +
  SANDBOX_SURVIVAL_OPENSHELL_DELETE_TIMEOUT_MS +
  SANDBOX_SURVIVAL_GATEWAY_STOP_BUDGET_MS +
  SANDBOX_SURVIVAL_GATEWAY_DESTROY_TIMEOUT_MS +
  SANDBOX_SURVIVAL_INSTALL_TIMEOUT_MS;

export const SANDBOX_SURVIVAL_LIFECYCLE_WORST_CASE_MS =
  2 * SANDBOX_SURVIVAL_SANDBOX_LIFECYCLE_TIMEOUT_MS;

// The rounded phase budgets contain the configured operation ceilings plus
// marker I/O, setup, diagnostics, and explicit headroom for each phase.
export const SANDBOX_SURVIVAL_PREPARATION_BUDGET_MS = 30 * MINUTE_MS;
export const SANDBOX_SURVIVAL_READINESS_BUDGET_MS = 15 * MINUTE_MS;
export const SANDBOX_SURVIVAL_LIFECYCLE_BUDGET_MS = 10 * MINUTE_MS;
export const SANDBOX_SURVIVAL_FINAL_VALIDATION_BUDGET_MS = 10 * MINUTE_MS;
export const SANDBOX_SURVIVAL_TEST_HEADROOM_MS = 5 * MINUTE_MS;

export const SANDBOX_SURVIVAL_TEST_TIMEOUT_MS =
  SANDBOX_SURVIVAL_PREPARATION_BUDGET_MS +
  SANDBOX_SURVIVAL_READINESS_BUDGET_MS +
  SANDBOX_SURVIVAL_LIFECYCLE_BUDGET_MS +
  SANDBOX_SURVIVAL_FINAL_VALIDATION_BUDGET_MS +
  SANDBOX_SURVIVAL_TEST_HEADROOM_MS;

export const SANDBOX_SURVIVAL_POST_TEST_CLEANUP_BUDGET_MS = 10 * MINUTE_MS;
export const SANDBOX_SURVIVAL_WORKFLOW_FINALIZATION_BUDGET_MS = 10 * MINUTE_MS;
export const SANDBOX_SURVIVAL_TARGET_TIMEOUT_MINUTES =
  (SANDBOX_SURVIVAL_TEST_TIMEOUT_MS +
    SANDBOX_SURVIVAL_POST_TEST_CLEANUP_BUDGET_MS +
    SANDBOX_SURVIVAL_WORKFLOW_FINALIZATION_BUDGET_MS) /
  MINUTE_MS;
