// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

const MINUTE_MS = 60_000;

export const ISSUE_9880_STAGING_LAUNCHABLE_ONBOARD_TIMEOUT_MS = 25 * MINUTE_MS;
export const ISSUE_9880_STAGING_LAUNCHABLE_SCENARIO_TIMEOUT_MS = 10 * MINUTE_MS;
export const ISSUE_9880_STAGING_LAUNCHABLE_CLEANUP_TIMEOUT_MS = 15 * MINUTE_MS;
export const ISSUE_9880_STAGING_LAUNCHABLE_TEST_TIMEOUT_MS = 100 * MINUTE_MS;
