// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const DEEPAGENTS_LEGACY_MCP_CONFIG_PATH = "/sandbox/.deepagents/.mcp.json";

export const DEEPAGENTS_LEGACY_CONFIG_HELPERS = [
  "LEGACY_MCP_MAX_BYTES = 262144",
  "def legacy_fingerprint(metadata):",
  "    return (metadata.st_dev, metadata.st_ino, metadata.st_size, metadata.st_mtime_ns, metadata.st_ctime_ns, metadata.st_mode, metadata.st_nlink, metadata.st_uid)",
  "def read_legacy_config(path):",
  "    flags = os.O_RDONLY | os.O_CLOEXEC | os.O_NONBLOCK | os.O_NOFOLLOW",
  "    descriptor = os.open(path, flags)",
  "    try:",
  "        before = os.fstat(descriptor)",
  "        linked = os.stat(path, follow_symlinks=False)",
  "        safe = (stat.S_ISREG(before.st_mode) and before.st_uid == os.getuid() and stat.S_IMODE(before.st_mode) == 0o600 and before.st_nlink == 1 and (before.st_dev, before.st_ino) == (linked.st_dev, linked.st_ino))",
  "        if not safe:",
  "            raise ValueError('legacy MCP config has unsafe ownership, mode, type, or links')",
  "        if before.st_size <= 0 or before.st_size > LEGACY_MCP_MAX_BYTES:",
  "            raise ValueError('legacy MCP config has invalid size')",
  "        chunks = []",
  "        remaining = before.st_size",
  "        while remaining:",
  "            chunk = os.read(descriptor, remaining)",
  "            if not chunk:",
  "                break",
  "            chunks.append(chunk)",
  "            remaining -= len(chunk)",
  "        after = os.fstat(descriptor)",
  "        linked_after = os.stat(path, follow_symlinks=False)",
  "        stable = (legacy_fingerprint(before) == legacy_fingerprint(after) and legacy_fingerprint(after) == legacy_fingerprint(linked_after))",
  "        if remaining or not stable:",
  "            raise ValueError('legacy MCP config changed while reading')",
  "    finally:",
  "        os.close(descriptor)",
  "    raw = b''.join(chunks).decode('utf-8')",
  "    data = strict_json_loads(raw)",
  "    return data, legacy_fingerprint(before)",
  "def assert_legacy_source_stable(path, identity):",
  "    if identity is None:",
  "        if os.path.lexists(path):",
  "            raise ValueError('legacy MCP config appeared during mutation')",
  "        return",
  "    current = os.stat(path, follow_symlinks=False)",
  "    safe = (stat.S_ISREG(current.st_mode) and current.st_uid == os.getuid() and stat.S_IMODE(current.st_mode) == 0o600 and current.st_nlink == 1 and legacy_fingerprint(current) == identity)",
  "    if not safe:",
  "        raise ValueError('legacy MCP config changed before mutation')",
];
