// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import fs from "node:fs";
import path from "node:path";

/**
 * `synthetic` treats the requested ForwardTcp service as owned.
 * `adaptive` observes fixture listeners and starts the fixture transport.
 * `real` keeps the production ownership proof.
 */
export type ForwardOwnerProof = "synthetic" | "adaptive" | "real";

export function syntheticForwardNodeOptions(
  directory: string,
  inheritedNodeOptions = process.env.NODE_OPTIONS,
  ownerProof: ForwardOwnerProof = "synthetic",
): string {
  const preload = path.join(directory, "synthetic-forward-platform.cjs");
  const ownerOverride =
    ownerProof === "synthetic"
      ? [
          'const Module = require("node:module");',
          "const originalLoad = Module._load;",
          "Module._load = function loadSyntheticForward(request, parent, isMain) {",
          "  const loaded = originalLoad.call(this, request, parent, isMain);",
          '  const normalizedRequest = String(request).replaceAll("\\\\", "/");',
          "  if (new RegExp('/adapters/openshell/forward-runtime(?:\\\\.[cm]?js|\\\\.ts)?$').test(normalizedRequest)) {",
          "    const createAdapter = loaded.createOpenShellForwardAdapterForAuthority;",
          "    loaded.createOpenShellForwardAdapterForAuthority = (...args) => {",
          "      const adapter = createAdapter(...args);",
          "      return { ...adapter, observeForwards: async ({ forwards }) =>",
          "        forwards.map((forward) => ({ state: 'owned', forward })) };",
          "    };",
          "  }",
          "  return loaded;",
          "};",
        ]
      : ownerProof === "adaptive"
        ? [
            'const Module = require("node:module");',
            'const net = require("node:net");',
            "const inspectSyntheticForward = (forward, expectedPid) => new Promise((resolve) => {",
            "  let settled = false;",
            '  const socket = net.createConnection({ host: "127.0.0.1", port: forward.port });',
            "  const finish = (value) => {",
            "    if (settled) return;",
            "    settled = true;",
            "    socket.destroy();",
            "    resolve(value);",
            "  };",
            "  socket.setTimeout(500);",
            "  socket.once('connect', () => finish({ state: 'owned', pid: expectedPid ?? 42101 }));",
            "  socket.once('timeout', () => finish({ state: 'indeterminate' }));",
            "  socket.once('error', (error) => finish(error.code === 'ECONNREFUSED'",
            "    ? { state: 'unbound' }",
            "    : { state: 'indeterminate' }));",
            "});",
            "const originalLoad = Module._load;",
            "Module._load = function loadAdaptiveForward(request, parent, isMain) {",
            "  const loaded = originalLoad.call(this, request, parent, isMain);",
            "  let resolvedRequest = request;",
            "  try { resolvedRequest = Module._resolveFilename(request, parent, isMain); } catch {}",
            '  const normalizedRequest = String(resolvedRequest).replaceAll("\\\\", "/");',
            "  if (new RegExp('/adapters/openshell/forward-runtime(?:\\\\.[cm]?js|\\\\.ts)?$').test(normalizedRequest)) {",
            "    const createAdapter = loaded.createOpenShellForwardAdapterForAuthority;",
            "    loaded.createOpenShellForwardAdapterForAuthority = (authority, options = {}) => {",
            "      const adapter = createAdapter(authority, options);",
            "      const observeForwards = async (request) => {",
            "        await request.assertCurrent?.();",
            "        const observations = await Promise.all(request.forwards.map(async (forward) => {",
            "          const inspected = await inspectSyntheticForward(forward);",
            "          if (inspected.state === 'owned') return { state: 'owned', forward };",
            "          if (inspected.state === 'unbound') return { state: 'absent', forward };",
            "          return { state: 'indeterminate', forward, error: {",
            "            kind: 'ownership',",
            "            message: 'NemoClaw could not prove OpenShell forward ownership.',",
            "          } };",
            "        }));",
            "        await request.assertCurrent?.();",
            "        return observations;",
            "      };",
            "      const startForward = async (request) => {",
            "        const [existing] = await observeForwards({",
            "          forwards: [request.forward],",
            "          assertCurrent: request.assertCurrent,",
            "        });",
            "        if (existing?.state === 'owned') return { state: 'reused', forward: request.forward };",
            "        if (existing?.state !== 'absent') return { state: 'refused', observation: existing };",
            "        await request.assertCurrent?.();",
            "        const executable = options.executable ?? process.env.NEMOCLAW_OPENSHELL_BIN ?? 'openshell';",
            "        const args = [",
            "          '--gateway', authority.gatewayName,",
            "          '--gateway-endpoint', authority.gatewayEndpoint,",
            "          '--workspace', authority.workspace,",
            "          'forward', 'service', request.forward.sandboxName,",
            "          '--target-port', String(request.forward.port),",
            "          '--target-host', '127.0.0.1',",
            "          '--local', request.forward.localHost + ':' + String(request.forward.port),",
            "        ];",
            "        let child;",
            "        let childError = null;",
            "        try {",
            "          child = require('node:child_process').spawn(executable, args, {",
            "            detached: true, env: process.env, shell: false, stdio: 'ignore',",
            "          });",
            "          child.once('error', (error) => { childError = error; });",
            "          child.unref();",
            "        } catch {",
            "          return { state: 'failed', forward: request.forward, effect: 'none', error: {",
            "            kind: 'transport', message: 'The OpenShell forward transport failed.',",
            "          } };",
            "        }",
            "        const deadline = Date.now() + (request.timeoutMs ?? 5000);",
            "        while (Date.now() < deadline) {",
            "          await request.assertCurrent?.();",
            "          if (childError) return { state: 'failed', forward: request.forward, effect: 'none', error: {",
            "            kind: 'transport', message: 'The OpenShell forward transport failed.',",
            "          } };",
            "          const inspected = await inspectSyntheticForward(request.forward, child.pid);",
            "          if (inspected.state === 'owned') return {",
            "            state: 'started',",
            "            forward: request.forward,",
            "            cleanup: async () => {",
            "              try { process.kill(-child.pid, 'SIGKILL'); } catch {}",
            "              return { state: 'released' };",
            "            },",
            "          };",
            "          await new Promise((resolve) => setTimeout(resolve, 25));",
            "        }",
            "        try { process.kill(-child.pid, 'SIGKILL'); } catch {}",
            "        return { state: 'failed', forward: request.forward, effect: 'possible', error: {",
            "          kind: 'timeout', message: 'The OpenShell forward operation timed out.',",
            "        } };",
            "      };",
            "      return { ...adapter, observeForwards, startForward };",
            "    };",
            "  }",
            "  return loaded;",
            "};",
          ]
        : [];
  fs.writeFileSync(
    preload,
    [
      "delete process.env.WSL_DISTRO_NAME;",
      "delete process.env.WSL_INTEROP;",
      'require("node:os").release = () => "6.8.0-linux";',
      ...ownerOverride,
      "",
    ].join("\n"),
    { mode: 0o600 },
  );
  return [inheritedNodeOptions, `--require=${JSON.stringify(preload)}`].filter(Boolean).join(" ");
}
