// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Generate the Pi model catalog from NemoClaw build-arg env vars.
//
// SECURITY: this file writes credential-free provider and model metadata.
// OpenShell supplies the managed route credential to the running agent, and the
// upstream provider credential never enters the sandbox.

import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const SUPPORTED_INFERENCE_API = "openai-completions";
const MANAGED_PROVIDER_ID = "openshell";
const MANAGED_PROVIDER_API_KEY = "nemoclaw-managed-inference";

type Settings = {
  model: string;
  baseUrl: string;
  providerKey: string;
  upstreamProvider: string;
  inferenceApi: string;
  contextWindow: number | null;
  maxTokens: number | null;
  reasoning: boolean | null;
};

type ManagedPiConfig = {
  text: string;
  model: string;
  baseUrl: string;
};

function readRequiredEnv(env: NodeJS.ProcessEnv, name: string): string {
  const value = env[name];
  if (!value) throw new Error(`${name} is required`);
  return value;
}

function normalizeMetadata(value: string, name: string): string {
  if (/[\p{Cc}\p{Cf}]/u.test(value)) {
    throw new Error(`${name} must not contain control characters.`);
  }
  const text = value.trim();
  if (!text) throw new Error(`${name} must not be empty.`);
  return text;
}

function normalizeInferenceApi(value: string | undefined): string {
  const text = normalizeMetadata(value || SUPPORTED_INFERENCE_API, "NEMOCLAW_INFERENCE_API");
  if (text !== SUPPORTED_INFERENCE_API) {
    throw new Error(`NEMOCLAW_INFERENCE_API must be ${SUPPORTED_INFERENCE_API} for Pi.`);
  }
  return text;
}

function normalizeInferenceBaseUrl(value: string): string {
  if (/[\r\n]/.test(value)) {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must not contain line breaks.");
  }
  const text = value.trim();
  let url: URL;
  try {
    url = new URL(text);
  } catch {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must be a valid URL.");
  }
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must use HTTP or HTTPS.");
  }
  if (url.username || url.password) {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must not include credentials.");
  }
  if (url.search || url.hash) {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must not include query strings or fragments.");
  }
  return text;
}

function normalizePositiveInteger(value: string | undefined, name: string): number | null {
  const text = (value ?? "").trim();
  if (!text) return null;
  if (!/^\d+$/u.test(text)) {
    throw new Error(`${name} must be a positive integer.`);
  }
  const parsed = Number(text);
  if (!Number.isSafeInteger(parsed) || parsed <= 0) {
    throw new Error(`${name} must be a positive integer.`);
  }
  return parsed;
}

function normalizeReasoning(value: string | undefined): boolean | null {
  const text = (value ?? "").trim();
  if (!text) return null;
  if (text === "true") return true;
  if (text === "false") return false;
  throw new Error('NEMOCLAW_REASONING must be "true" or "false".');
}

function readSettings(env: NodeJS.ProcessEnv): Settings {
  const providerKey = normalizeMetadata(
    env.NEMOCLAW_INFERENCE_PROVIDER_ID || env.NEMOCLAW_PROVIDER_KEY || "inference",
    "NEMOCLAW_INFERENCE_PROVIDER_ID",
  );
  return {
    model: normalizeMetadata(readRequiredEnv(env, "NEMOCLAW_MODEL"), "NEMOCLAW_MODEL"),
    baseUrl: normalizeInferenceBaseUrl(
      env.NEMOCLAW_INFERENCE_BASE_URL || "https://inference.local/v1",
    ),
    providerKey,
    upstreamProvider: normalizeMetadata(
      env.NEMOCLAW_UPSTREAM_PROVIDER || providerKey,
      "NEMOCLAW_UPSTREAM_PROVIDER",
    ),
    inferenceApi: normalizeInferenceApi(env.NEMOCLAW_INFERENCE_API),
    contextWindow: normalizePositiveInteger(env.NEMOCLAW_CONTEXT_WINDOW, "NEMOCLAW_CONTEXT_WINDOW"),
    maxTokens: normalizePositiveInteger(env.NEMOCLAW_MAX_TOKENS, "NEMOCLAW_MAX_TOKENS"),
    reasoning: normalizeReasoning(env.NEMOCLAW_REASONING),
  };
}

function buildModel(settings: Settings): Record<string, unknown> {
  const model: Record<string, unknown> = { id: settings.model };
  if (settings.contextWindow !== null) model.contextWindow = settings.contextWindow;
  if (settings.maxTokens !== null) model.maxTokens = settings.maxTokens;
  if (settings.reasoning !== null) model.reasoning = settings.reasoning;
  return model;
}

function buildConfig(settings: Settings): ManagedPiConfig {
  const config = {
    $comment: `Generated by NemoClaw. This file contains no provider secrets. NemoClaw provider route: ${settings.providerKey}; upstream provider: ${settings.upstreamProvider}; API: ${settings.inferenceApi}.`,
    defaultModel: settings.model,
    providers: {
      [MANAGED_PROVIDER_ID]: {
        api: settings.inferenceApi,
        apiKey: MANAGED_PROVIDER_API_KEY,
        baseUrl: settings.baseUrl,
        models: [buildModel(settings)],
      },
    },
  };
  return {
    text: `${JSON.stringify(config, null, 2)}\n`,
    model: settings.model,
    baseUrl: settings.baseUrl,
  };
}

function main(): void {
  const settings = readSettings(process.env);
  const configDir = join(homedir(), ".pi", "agent");
  mkdirSync(configDir, { recursive: true, mode: 0o700 });

  const configPath = join(configDir, "models.json");
  const config = buildConfig(settings);
  writeFileSync(configPath, config.text, { mode: 0o600 });
  chmodSync(configPath, 0o600);

  console.log(`[config] Wrote ${configPath} (model=${config.model}, base_url=${config.baseUrl})`);
}

main();
