// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/** Exact shipped files admitted by the schema-7 Hermes Dockerfile COPY contract. */
export const HERMES_PORTABLE_BUILD_CONTEXT_FILES = [
  { path: "agents/hermes/build-mcp-digest.py", mode: "100644" },
  { path: "agents/hermes/config/build-env.ts", mode: "100644" },
  { path: "agents/hermes/config/generate.ts", mode: "100644" },
  { path: "agents/hermes/config/hermes-env.ts", mode: "100644" },
  { path: "agents/hermes/config/managed-policy.ts", mode: "100644" },
  { path: "agents/hermes/config/managed-tool-gateway.ts", mode: "100644" },
  { path: "agents/hermes/config/model-specific-setup.ts", mode: "100644" },
  { path: "agents/hermes/config/object-record.ts", mode: "100644" },
  { path: "agents/hermes/config/upstream-header.ts", mode: "100644" },
  { path: "agents/hermes/config/write-config.ts", mode: "100644" },
  { path: "agents/hermes/config/yaml.ts", mode: "100644" },
  { path: "agents/hermes/cron-restore-control.py", mode: "100644" },
  { path: "agents/hermes/dashboard-external-host.patch", mode: "100644" },
  { path: "agents/hermes/Dockerfile", mode: "100644" },
  { path: "agents/hermes/finalize-tirith-marker.py", mode: "100755" },
  { path: "agents/hermes/generate-config.ts", mode: "100644" },
  { path: "agents/hermes/hermes-cli-adapter-v1.json", mode: "100644" },
  { path: "agents/hermes/hermes-wrapper.py", mode: "100755" },
  { path: "agents/hermes/host/managed-tool-gateway-matrix.json", mode: "100644" },
  { path: "agents/hermes/image-build-probes.py", mode: "100644" },
  { path: "agents/hermes/managed_policy.py", mode: "100644" },
  { path: "agents/hermes/mcp-config-transaction.py", mode: "100755" },
  { path: "agents/hermes/patch-cron-execution-runtime.py", mode: "100755" },
  { path: "agents/hermes/patch-cron-restore-drain.py", mode: "100755" },
  { path: "agents/hermes/patch-discord-recovery-permissions.py", mode: "100755" },
  { path: "agents/hermes/patch-gateway-process-identity.py", mode: "100755" },
  { path: "agents/hermes/patch-gateway-runtime-metadata.py", mode: "100755" },
  { path: "agents/hermes/patch-hermes-sqlite-temp-store.py", mode: "100755" },
  { path: "agents/hermes/patch-langfuse-credentials.mts", mode: "100644" },
  { path: "agents/hermes/patch-neutral-platform-env-activation.py", mode: "100755" },
  { path: "agents/hermes/patch-profile-policy-defaults.py", mode: "100755" },
  { path: "agents/hermes/patch-session-list-preview.py", mode: "100755" },
  { path: "agents/hermes/plugin/__init__.py", mode: "100644" },
  { path: "agents/hermes/plugin/plugin.yaml", mode: "100644" },
  { path: "agents/hermes/runtime-config-guard.py", mode: "100755" },
  { path: "agents/hermes/runtime-boundaries.patch", mode: "100644" },
  { path: "agents/hermes/security-dependencies.patch", mode: "100644" },
  { path: "agents/hermes/seed-dashboard-config.py", mode: "100755" },
  { path: "agents/hermes/start.sh", mode: "100755" },
  { path: "agents/hermes/validate-cli-adapter.py", mode: "100755" },
  { path: "agents/hermes/validate-env-secret-boundary.py", mode: "100755" },
  { path: "nemoclaw-blueprint/blueprint.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/model-specific-setup/hermes/README.md", mode: "100644" },
  {
    path: "nemoclaw-blueprint/model-specific-setup/openclaw/gemini-3-managed-inference.json",
    mode: "100644",
  },
  {
    path: "nemoclaw-blueprint/model-specific-setup/openclaw/gpt-5-o-series-managed-inference.json",
    mode: "100644",
  },
  {
    path: "nemoclaw-blueprint/model-specific-setup/openclaw/kimi-k2.6-managed-inference.json",
    mode: "100644",
  },
  {
    path: "nemoclaw-blueprint/model-specific-setup/openclaw/nemotron-3-super-120b-managed-inference.json",
    mode: "100644",
  },
  {
    path: "nemoclaw-blueprint/model-specific-setup/openclaw/nemotron-3-ultra-managed-inference.json",
    mode: "100644",
  },
  { path: "nemoclaw-blueprint/model-specific-setup/README.md", mode: "100644" },
  { path: "nemoclaw-blueprint/model-specific-setup/schema.json", mode: "100644" },
  { path: "nemoclaw-blueprint/openclaw-plugins/gemini-inference-compat/index.ts", mode: "100644" },
  {
    path: "nemoclaw-blueprint/openclaw-plugins/gemini-inference-compat/openclaw.plugin.json",
    mode: "100644",
  },
  { path: "nemoclaw-blueprint/openclaw-plugins/kimi-inference-compat/index.js", mode: "100644" },
  {
    path: "nemoclaw-blueprint/openclaw-plugins/kimi-inference-compat/openclaw.plugin.json",
    mode: "100644",
  },
  { path: "nemoclaw-blueprint/policies/openclaw-sandbox.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/brave.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/brew.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/claude-code.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/github.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/gmail.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/huggingface.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/jira.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/local-inference.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/local-memory.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/nous-audio.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/nous-browser.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/nous-code.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/nous-image.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/nous-web.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/npm.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/observability-otlp-local.yaml", mode: "100644" },
  {
    path: "nemoclaw-blueprint/policies/presets/openclaw-diagnostics-otel-local.yaml",
    mode: "100644",
  },
  { path: "nemoclaw-blueprint/policies/presets/openclaw-pricing.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/outlook.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/personal-open-internet.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/public-reference.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/pypi.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/tavily.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/presets/weather.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/policies/tiers.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/private-networks.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/provider-profiles/brave.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/provider-profiles/entra-runtime-v1.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/provider-profiles/langfuse-hermes-v1.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/provider-profiles/nemoclaw-mcp-v1.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/provider-profiles/openai.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/provider-profiles/okta-runtime-v1.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/provider-profiles/tavily-hermes-v1.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/provider-profiles/tavily.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/router/llm-router", mode: "160000" },
  { path: "nemoclaw-blueprint/router/pool-config.yaml", mode: "100644" },
  { path: "nemoclaw-blueprint/scripts/ciao-network-guard.js", mode: "100644" },
  { path: "nemoclaw-blueprint/scripts/http-proxy-fix.js", mode: "100644" },
  { path: "nemoclaw-blueprint/scripts/nemotron-inference-fix.js", mode: "100644" },
  { path: "nemoclaw-blueprint/scripts/sandbox-safety-net.js", mode: "100644" },
  { path: "nemoclaw-blueprint/tsconfig.json", mode: "100644" },
  { path: "scripts/gateway-control.sh", mode: "100755" },
  { path: "scripts/lib/bundled-npm-package.mts", mode: "100644" },
  { path: "scripts/lib/corporate-ca-runtime.sh", mode: "100755" },
  { path: "scripts/lib/entrypoint-env-wrapper.sh", mode: "100755" },
  { path: "scripts/lib/gateway-supervisor.sh", mode: "100755" },
  { path: "scripts/lib/openclaw-npm-remediation.mts", mode: "100755" },
  { path: "scripts/lib/patch-bundled-npm-ip-address.mts", mode: "100755" },
  { path: "scripts/lib/reviewed-npm-archive.mts", mode: "100755" },
  { path: "scripts/lib/sandbox-init.sh", mode: "100755" },
  { path: "scripts/lib/sandbox-rlimits.sh", mode: "100644" },
  { path: "scripts/managed-bootstrap-entrypoint.c", mode: "100644" },
  { path: "scripts/managed-bootstrap-trampoline.sh", mode: "100644" },
  { path: "scripts/managed-gateway-control.py", mode: "100755" },
  { path: "scripts/managed-startup-hold.sh", mode: "100755" },
  { path: "scripts/patch-bundled-npm-brace-expansion.mts", mode: "100755" },
  { path: "scripts/patch-bundled-npm-tar.mts", mode: "100755" },
  {
    path: "src/lib/actions/sandbox/openshell-child-visible-credentials.v0.0.106.json",
    mode: "100644",
  },
  { path: "src/lib/hermes-managed-route.ts", mode: "100644" },
  { path: "src/lib/messaging/AGENTS.md", mode: "100644" },
  { path: "src/lib/messaging/applier/agent-config-remove.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/agent-config.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/build/messaging-build-applier.mts", mode: "100755" },
  { path: "src/lib/messaging/applier/conflict-detection-entry.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection-multi-credential.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection-overlap.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection-plan.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection-slack-gateway.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection/entries.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection/index.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection/manifest-metadata.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection/plan.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection/registry.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection/slack-socket-mode.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/conflict-detection/types.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/credential-env-cleanup.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/hook-phases.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/hook-phases.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/host-state-applier.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/host-state-applier.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/index.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/openclaw-plugin-allow.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/openclaw-plugin-allow.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/openshell-provider.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/plan-filter.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/policy.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/setup-applier-credential-env.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/setup-applier.test.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/setup-applier.ts", mode: "100644" },
  { path: "src/lib/messaging/applier/types.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/built-ins.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/channel-health.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/credential-injection.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/hooks/index.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/hooks/openclaw-bridge-health.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/manifest.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/policy/hermes.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/policy/openclaw.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/provider-profile/hermes.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/rendered-config-parser.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/rendered-config-parser.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/discord/template-resolver.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/hooks/index.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/hooks/runtime-deps.ts", mode: "100644" },
  {
    path: "src/lib/messaging/channels/googlechat/hooks/service-account-token-paste.test.ts",
    mode: "100644",
  },
  {
    path: "src/lib/messaging/channels/googlechat/hooks/service-account-token-paste.ts",
    mode: "100644",
  },
  {
    path: "src/lib/messaging/channels/googlechat/hooks/tunnel-audience-gate.test.ts",
    mode: "100644",
  },
  { path: "src/lib/messaging/channels/googlechat/hooks/tunnel-audience-gate.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/hooks/tunnel-runtime.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/hooks/tunnel-runtime.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/manifest.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/policy.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/policy/hermes.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/policy/openclaw.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/provider-profile/hermes.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/provider-profile/openclaw.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/rendered-config-parser.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/runtime-contract.test.ts", mode: "100644" },
  {
    path: "src/lib/messaging/channels/googlechat/runtime/googlechat-outbound-auth.test.ts",
    mode: "100644",
  },
  {
    path: "src/lib/messaging/channels/googlechat/runtime/googlechat-outbound-auth.ts",
    mode: "100644",
  },
  {
    path: "src/lib/messaging/channels/googlechat/runtime/googlechat-trusted-proxy-fetch.test.ts",
    mode: "100644",
  },
  {
    path: "src/lib/messaging/channels/googlechat/runtime/googlechat-trusted-proxy-fetch.ts",
    mode: "100644",
  },
  { path: "src/lib/messaging/channels/googlechat/runtime/hermes-adapter.py", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/runtime/hermes-adapter.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/template-resolver.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/template-resolver.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/tunnel/lifecycle.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/tunnel/lifecycle.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/tunnel/pid-dir.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/tunnel/proxy.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/googlechat/tunnel/proxy.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/index.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/manifests.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/metadata.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/metadata.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/openclaw-bridge-health.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/openclaw-bridge-health.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/policy.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/policy.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/rendered-config-parser-utils.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/rendered-config-parser.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/hooks/credential-validation.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/hooks/credential-validation.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/hooks/index.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/hooks/openclaw-bridge-health.ts", mode: "100644" },
  {
    path: "src/lib/messaging/channels/slack/hooks/socket-mode-gateway-conflict.test.ts",
    mode: "100644",
  },
  {
    path: "src/lib/messaging/channels/slack/hooks/socket-mode-gateway-conflict.ts",
    mode: "100644",
  },
  {
    path: "src/lib/messaging/channels/slack/hooks/socket-mode-gateway-status.test.ts",
    mode: "100644",
  },
  { path: "src/lib/messaging/channels/slack/hooks/socket-mode-gateway-status.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/hooks/status-health.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/hooks/status-health.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/hooks/validate-credentials.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/hooks/validate-credentials.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/manifest.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/policy/hermes.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/policy/openclaw.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/rendered-config-parser.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/runtime/slack-channel-guard.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/slack/template-resolver.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/teams/contract.ts", mode: "100644" },
  {
    path: "src/lib/messaging/channels/teams/hooks/host-forward-port-conflict.test.ts",
    mode: "100644",
  },
  { path: "src/lib/messaging/channels/teams/hooks/host-forward-port-conflict.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/teams/hooks/index.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/teams/manifest.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/teams/policy/hermes.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/teams/policy/openclaw.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/teams/rendered-config-parser.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/teams/runtime/msteams-message-hints.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/teams/template-resolver.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/allowlist-aliases.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/allowlist-aliases.ts", mode: "100644" },
  {
    path: "src/lib/messaging/channels/telegram/hooks/gateway-conflict-status.test.ts",
    mode: "100644",
  },
  { path: "src/lib/messaging/channels/telegram/hooks/gateway-conflict-status.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/get-me-reachability.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/get-me-reachability.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/index.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/openclaw-bridge-health.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/status-health-eval.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/status-health-eval.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/status-health.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/hooks/status-health.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/manifest.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/policy/hermes.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/policy/openclaw.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/rendered-config-parser.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/rendered-config-parser.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/runtime/telegram-diagnostics.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/template-resolver.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/telegram/template-resolver.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/template-resolver-utils.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/template-resolver.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/contract.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/hooks/health-check.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/hooks/host-qr-login-runtime.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/hooks/ilink-login.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/hooks/implementations.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/hooks/index.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/hooks/seed-openclaw-account.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/ilink-base-url.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/login.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/login.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/manifest.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/policy/hermes.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/policy/openclaw.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/qr.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/qr.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/rendered-config-parser.ts", mode: "100644" },
  {
    path: "src/lib/messaging/channels/wechat/runtime/wechat-account-placeholder.test.ts",
    mode: "100644",
  },
  {
    path: "src/lib/messaging/channels/wechat/runtime/wechat-account-placeholder.ts",
    mode: "100644",
  },
  { path: "src/lib/messaging/channels/wechat/runtime/wechat-diagnostics.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/wechat/template-resolver.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/hooks/index.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/hooks/status-health-eval.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/hooks/status-health-eval.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/hooks/status-health.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/hooks/status-health.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/manifest.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/policy/hermes.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/policy/openclaw.yaml", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/rendered-config-parser.ts", mode: "100644" },
  {
    path: "src/lib/messaging/channels/whatsapp/runtime/whatsapp-qr-compact-test-helpers.ts",
    mode: "100644",
  },
  {
    path: "src/lib/messaging/channels/whatsapp/runtime/whatsapp-qr-compact.test.ts",
    mode: "100644",
  },
  { path: "src/lib/messaging/channels/whatsapp/runtime/whatsapp-qr-compact.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/template-resolver.test.ts", mode: "100644" },
  { path: "src/lib/messaging/channels/whatsapp/template-resolver.ts", mode: "100644" },
  { path: "src/lib/messaging/clone-rebind.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/engines/agent-render-engine.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/engines/build-step-engine.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/engines/credential-binding-engine.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/engines/health-check-engine.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/engines/host-forward-engine.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/engines/policy-resolver.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/engines/runtime-setup-engine.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/engines/state-update-engine.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/engines/template.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/index.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/manifest-compiler.test.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/manifest-compiler.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/types.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/workflow-planner-hermes-slack.test.ts", mode: "100644" },
  {
    path: "src/lib/messaging/compiler/workflow-planner-removal-tombstone.test.ts",
    mode: "100644",
  },
  { path: "src/lib/messaging/compiler/workflow-planner.test.ts", mode: "100644" },
  { path: "src/lib/messaging/compiler/workflow-planner.ts", mode: "100644" },
  { path: "src/lib/messaging/diagnostics.test.ts", mode: "100644" },
  { path: "src/lib/messaging/diagnostics.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/builtins.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/common/config-prompt.test.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/common/config-prompt.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/common/index.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/common/static-outputs.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/common/token-paste.test.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/common/token-paste.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/errors.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/hook-runner.test.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/hook-runner.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/index.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/registry.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/status-runner.test.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/status-runner.ts", mode: "100644" },
  { path: "src/lib/messaging/hooks/types.ts", mode: "100644" },
  { path: "src/lib/messaging/host-forward.ts", mode: "100644" },
  { path: "src/lib/messaging/hydration.ts", mode: "100644" },
  { path: "src/lib/messaging/index.ts", mode: "100644" },
  { path: "src/lib/messaging/manifest/index.ts", mode: "100644" },
  { path: "src/lib/messaging/manifest/registry.test.ts", mode: "100644" },
  { path: "src/lib/messaging/manifest/registry.ts", mode: "100644" },
  { path: "src/lib/messaging/manifest/types.test.ts", mode: "100644" },
  { path: "src/lib/messaging/manifest/types.ts", mode: "100644" },
  { path: "src/lib/messaging/managed-startup-placeholders.test.ts", mode: "100644" },
  { path: "src/lib/messaging/managed-startup-placeholders.ts", mode: "100644" },
  { path: "src/lib/messaging/persisted-placeholders.test.ts", mode: "100644" },
  { path: "src/lib/messaging/persisted-placeholders.ts", mode: "100644" },
  { path: "src/lib/messaging/persistence.ts", mode: "100644" },
  { path: "src/lib/messaging/plan-authority.test.ts", mode: "100644" },
  { path: "src/lib/messaging/plan-authority.ts", mode: "100644" },
  { path: "src/lib/messaging/plan-validation.test.ts", mode: "100644" },
  { path: "src/lib/messaging/plan-validation.ts", mode: "100644" },
  { path: "src/lib/messaging/post-agent-install-selection.test.ts", mode: "100644" },
  { path: "src/lib/messaging/post-agent-install-selection.ts", mode: "100644" },
  { path: "src/lib/messaging/provider-placeholders.ts", mode: "100644" },
  { path: "src/lib/messaging/provider-profile.test.ts", mode: "100644" },
  { path: "src/lib/messaging/provider-profile.ts", mode: "100644" },
  { path: "src/lib/messaging/README.md", mode: "100644" },
  { path: "src/lib/messaging/utils.test.ts", mode: "100644" },
  { path: "src/lib/messaging/utils.ts", mode: "100644" },
  { path: "src/lib/tool-disclosure.ts", mode: "100644" },
  {
    path: "tools/mcp-tool-discovery-runtime/npm-cache-seed/tar-7.5.21.tgz",
    mode: "100644",
  },
  {
    path: "tools/mcp-tool-discovery-runtime/reviewed-runtime-bundle/managed-startup-image-runtime.bundle",
    mode: "100644",
  },
  {
    path: "tools/mcp-tool-discovery-runtime/reviewed-runtime-bundle/mcp-tool-discovery/BUNDLED_PACKAGES.json",
    mode: "100644",
  },
  {
    path: "tools/mcp-tool-discovery-runtime/reviewed-runtime-bundle/mcp-tool-discovery/mcp-tool-discovery.bundle",
    mode: "100644",
  },
  {
    path: "tools/mcp-tool-discovery-runtime/reviewed-runtime-bundle/mcp-tool-discovery/THIRD_PARTY_LICENSES.txt",
    mode: "100644",
  },
] as const;
